#!/bin/bash
# Session-start hook for Claude Code on the web. Sets up the .NET API
# (apps/api) and the Android/Kotlin toolchain (apps/android) so both are
# ready to build and test on first invocation.
# (The Flutter app was removed in P5.3 — web + Android are the product.)
#
# Idempotent: every install step probes for the artefact first, so the
# hook is safe to re-run.
set -euo pipefail

if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

# ---------------------------------------------------------------------------
# 2. .NET 10 SDK via Microsoft's apt repo.
# ---------------------------------------------------------------------------
if ! command -v dotnet >/dev/null 2>&1; then
  if ! dpkg -s packages-microsoft-prod >/dev/null 2>&1; then
    TMP_DEB="$(mktemp --suffix=.deb)"
    curl -fsSL https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb -o "$TMP_DEB"
    dpkg -i "$TMP_DEB"
    rm -f "$TMP_DEB"
  fi
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends dotnet-sdk-10.0
fi

# ---------------------------------------------------------------------------
# 3. Docker daemon for Testcontainers (api behaviour tests).
# ---------------------------------------------------------------------------
if command -v dockerd >/dev/null 2>&1; then
  if ! docker info >/dev/null 2>&1; then
    nohup dockerd >/tmp/dockerd.log 2>&1 &
    for _ in $(seq 1 30); do
      docker info >/dev/null 2>&1 && break
      sleep 1
    done
  fi
fi

# ---------------------------------------------------------------------------
# 4. Restore NuGet packages.
# ---------------------------------------------------------------------------
if [ -f "$CLAUDE_PROJECT_DIR/apps/api/Turboapi.sln" ]; then
  (cd "$CLAUDE_PROJECT_DIR/apps/api" && dotnet restore Turboapi.sln)
fi

# ---------------------------------------------------------------------------
# 5. Android SDK + NDK, and the Rust cross-compilation toolchain.
#
# Without this a session can read the Android app but not compile a line
# of it, and `:core:turbomap-android` / `:core:routing-android` cannot be
# built at all — their Kotlin bindings and per-ABI `.so` are generated by
# Gradle from Rust crates in apps/tileserver and apps/turbomap.
#
# That gap is not theoretical. `turbo-route-ffi`'s Android-only
# `init_logging` referenced `log::LevelFilter` without depending on
# `log`, and nothing caught it for as long as no Android target existed:
# the code sits behind `cfg(target_os = "android")`, so a workstation
# `cargo check` never looks at it. The first cross-compile found it in
# seconds.
#
# Roughly 3 GB and, cold, ~10 minutes. Every step probes first, so a warm
# container skips the lot in under a second.
# ---------------------------------------------------------------------------
# `protoc`, for `turbomap-mvt`'s prost build script. Not an Android
# dependency as such — but `:core:turbomap-android` cross-compiles that
# crate, so without it half the app's native modules do not build and the
# error names protobuf rather than anything a reader would connect to
# Android.
if ! command -v protoc >/dev/null 2>&1; then
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends \
    protobuf-compiler >/dev/null 2>&1 || true
fi

ANDROID_SDK_DIR="${ANDROID_SDK_ROOT:-/opt/android-sdk}"

# Versions are pinned rather than "latest" so two containers built weeks
# apart compile the same bytes. `compileSdk`/`TURBO_COMPILE_SDK` lives in
# apps/android/build-logic; keep this in step with it.
ANDROID_PLATFORM="platforms;android-37.0"
ANDROID_BUILD_TOOLS="build-tools;37.0.0"
ANDROID_NDK_VERSION="28.2.13676358"

if [ -d "$CLAUDE_PROJECT_DIR/apps/android" ]; then
  export ANDROID_HOME="$ANDROID_SDK_DIR"
  export ANDROID_SDK_ROOT="$ANDROID_SDK_DIR"
  SDKMANAGER="$ANDROID_SDK_DIR/cmdline-tools/latest/bin/sdkmanager"

  if [ ! -x "$SDKMANAGER" ]; then
    TMP_ZIP="$(mktemp --suffix=.zip)"
    TMP_DIR="$(mktemp -d)"
    curl -fsSL -o "$TMP_ZIP" \
      "https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
    unzip -q "$TMP_ZIP" -d "$TMP_DIR"
    mkdir -p "$ANDROID_SDK_DIR/cmdline-tools"
    mv "$TMP_DIR/cmdline-tools" "$ANDROID_SDK_DIR/cmdline-tools/latest"
    rm -rf "$TMP_ZIP" "$TMP_DIR"
  fi

  # `yes |` because the licence prompt is interactive and there is no
  # human here. Accepting Google's SDK terms is the price of the SDK.
  yes | "$SDKMANAGER" --licenses >/dev/null 2>&1 || true

  # One `sdkmanager` invocation per missing component, skipped entirely
  # when the directory is already there — it is slow even for a no-op.
  ANDROID_WANTED=()
  [ -d "$ANDROID_SDK_DIR/platform-tools" ] || ANDROID_WANTED+=("platform-tools")
  [ -d "$ANDROID_SDK_DIR/platforms/${ANDROID_PLATFORM#platforms;}" ] \
    || ANDROID_WANTED+=("$ANDROID_PLATFORM")
  [ -d "$ANDROID_SDK_DIR/build-tools/${ANDROID_BUILD_TOOLS#build-tools;}" ] \
    || ANDROID_WANTED+=("$ANDROID_BUILD_TOOLS")
  [ -d "$ANDROID_SDK_DIR/ndk/$ANDROID_NDK_VERSION" ] \
    || ANDROID_WANTED+=("ndk;$ANDROID_NDK_VERSION")
  if [ ${#ANDROID_WANTED[@]} -gt 0 ]; then
    "$SDKMANAGER" --install "${ANDROID_WANTED[@]}" >/dev/null 2>&1
  fi

  # Gradle finds the SDK through local.properties; it is gitignored, so
  # it has to be written per container rather than committed.
  if ! grep -qs "^sdk.dir=" "$CLAUDE_PROJECT_DIR/apps/android/local.properties" 2>/dev/null; then
    echo "sdk.dir=$ANDROID_SDK_DIR" >> "$CLAUDE_PROJECT_DIR/apps/android/local.properties"
  fi

  # Rust → Android. The targets go on the toolchain apps/tileserver PINS
  # (rust-toolchain.toml), not the default one: `rustup target add` with
  # no --toolchain installs for whatever is active in the current
  # directory, which is the wrong toolchain from anywhere but there, and
  # the failure is a confusing "can't find crate for `core`".
  if command -v rustup >/dev/null 2>&1; then
    RUST_PINNED="$(cd "$CLAUDE_PROJECT_DIR/apps/tileserver" 2>/dev/null && rustup show active-toolchain 2>/dev/null | cut -d" " -f1 || true)"
    for target in aarch64-linux-android armv7-linux-androideabi x86_64-linux-android; do
      if [ -n "$RUST_PINNED" ]; then
        rustup target add --toolchain "$RUST_PINNED" "$target" >/dev/null 2>&1 || true
      fi
      rustup target add "$target" >/dev/null 2>&1 || true
    done
  fi

  # cargo-ndk drives the per-ABI cross-compile the Gradle modules invoke.
  if ! command -v cargo-ndk >/dev/null 2>&1; then
    cargo install cargo-ndk --locked >/dev/null 2>&1 || true
  fi
fi
