//! `/sprite{@2x}.{json,png}` — the icon sprite sheet for MapLibre GL.
//!
//! The basemap style's `place` layers reference `icon-image` keyed off the
//! anchor `kind`; this serves the matching atlas (generated by
//! `turbo-tiles-raster`). Four routes — json/png × 1×/2× — the same set
//! MapLibre requests. Cached by the edge worker (`/sprite*` allowlist).

use axum::body::Body;
use axum::http::{header, HeaderValue, StatusCode};
use axum::response::Response;

use crate::error::ApiError;

fn build(ratio: u32, png: bool) -> Result<Response, ApiError> {
    let (png_bytes, json) =
        turbo_tiles_raster::build_sprite(ratio).map_err(|e| ApiError::Db(e.to_string()))?;
    let (body, ctype) = if png {
        (Body::from(png_bytes), "image/png")
    } else {
        (Body::from(json), "application/json")
    };
    let mut resp = Response::builder()
        .status(StatusCode::OK)
        .body(body)
        .unwrap();
    let h = resp.headers_mut();
    h.insert(header::CONTENT_TYPE, HeaderValue::from_static(ctype));
    h.insert(
        header::CACHE_CONTROL,
        HeaderValue::from_static("public, max-age=86400, stale-while-revalidate=604800"),
    );
    Ok(resp)
}

pub async fn json_1x() -> Result<Response, ApiError> {
    build(1, false)
}
pub async fn png_1x() -> Result<Response, ApiError> {
    build(1, true)
}
pub async fn json_2x() -> Result<Response, ApiError> {
    build(2, false)
}
pub async fn png_2x() -> Result<Response, ApiError> {
    build(2, true)
}
