---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: r2-backup-creds
  namespace: turbo-prod
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAJBp/R7PGP9M15gCb1oYSTiMWN8ElocQegmkSRvjpcXeIa+5GGS1Y5GcYMScQVedNEnHL2s/8BbxYg7xvcD1Sc35/jz2FvKGp3NGdM6Y7HX0/9GGbjXqo9I3aXw+hCM0ZDvibFgZDzUkDHXx4rXlYVdcvTAPRIQy3EFGsigERcx/Zf8eno6Hoc+oH9dlo4PJxF+qCk5Q98Np5U3HgGMbgKEd3JWsz5LCQ2Q8QF5V9DRcITNdFz8QUEqu7cH0Fbffab/rUn4iOylL/0+4z0w/U94OOgODhyfkxKIQmu2DNbIJb0wb/M+egrWSa9s9KkQGy6we4hetAnwSOCPQg2XNqbIEn8GjrpziURNqV+UTt4/Lkt5hlGd3uECPpZlO1rkNNfygdrvSClLTeW9VyRmPiMo1GDqWwqSoC3iKhmUEbmGf/uy5Xs8yRI3bzSb52duGVXJVa+TnLzJ2FutvMipZfhlU/DjZPRZY9ZnQefEdaEGYLi8Ad8/+XImImw5kJ9Y/we9Kob1j94hmzj4il6kJ9GYLq7BRc6ioLx/JVxeh1FTpsIfskbxRJR1oOGo+thUpqYqqhPBY83aVG27bODgovVwWxvrAMVLK0aXyFCXApQ4Zadxguo7LBrnSlE2PXb8212qMcPxjLzZnLvbTTOsaFtWx4yo/dF4kl4lmcYKPvIoYUXBPZMq3ucmO0Y/BzLP29y+jXlgcE7vI/F9BVjdusm9Od7L8zvSOrLa7qt3LHloA==
    ACCESS_SECRET_KEY: AgBhZU04VcEEPMPpZQzcV1BbJqH/Xmv6ZxfRvSDEsh3VQneyghvzIk3bzLUg93tOAXPNGiWyM6vhVulnrA76JrAFMg5kPQ+FT+naNE1K/0oC/QlYWzzKlDvfuwNzCBhDMDr8YITb8uagz3oaE09EhKta3yxZ8WZU5Xa6bA5g6WaI5816r2Gh3HMG6FziLILZ6UZ/wt5sF+xJh+E4UgdUgso+IfBf8xwYzYLbDqCuamjRDl8TVcoY0U69TYgPlmJRkRicPe9UN+kn+NOARlpa/qPRV2dLwlFpLHraO0UNPTy6fPsSAYqNhGbrExst2MVaYlYEqiSnKJ2AxHT8OYuyu1Q9EBRT2zQKUx+kOYjhsde+P7VR5+JC+97iuvS4DrIZ5BrwolQE7U+VOPuOWHN7abfkeG1jHhoSTCnGjUne7aESTv+i3QEfUA8Ap5SQFBOpJc5W5v9vREHjzqy8tKczUtd5ULhz2G6/UgPR15C/3WkzY4wUa2c54w42v21B2aBjRpj4t0kRsg3oARZ1w8CoMjJcbQLDdg1Hm8JiVPuj2lIVM9AChvItZGsgu5NdeiNpxNUNiZ/z4awII+l3jXoajxdm5+d11ikTM2EiThQH/hmPiv57BGwHtw4y9rbOrrqlbNxDvDGgmt4sjt/nGcddebzqUiRAKQUdzcS8SRbVUKHHtKSmOSD8fM7Y9W1KsHuqhBPLtjfjD9j/JDmH2e4vO8Kte2lFVMbxDjbSUnpf5SU1qFJiEBJ2/5qqRc9PJqQZRZ0mBxacA15xVdicd4RkyX6q
  template:
    metadata:
      creationTimestamp: null
      name: r2-backup-creds
      namespace: turbo-prod
