apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth-secrets
  namespace: turbo-prod
spec:
  encryptedData:
    jwt-key: AgBVs2zVCiBUVyoUSC1GKM07E92m3GQ+8JxPm0kZ3BviJCoaUwALyb9wU5ir5LYsEbbEe2VjkY3GCBrKVrYQEj2/2YBH9xsHynpFqXHe5DoCPtqbK8tdypLjQyGJRg0ImR1fcIFktsgchr20tP8IaVNMfZOOhPaYAw348Eq6PBI3oD8bev3YmiRmNFRQsIJZRPL6eHJcMek7FnFBgXdI/37FE7LuQCSjBv7qzmHI566P9wSwarfyLqltj650GLd/PrVIBRpYhJ9is0qOpeUrqmdOCA4LAlVjBJuC773XhnsQ1mrEj+ObIWKxKfRuwmZQYg/dd77/G9s12FNefiwr5s1vAuHF/8v/5GjEUjstJ2LAUF0juLCP57ey6eHEEqqdyG/GKuu0wNTLqGn2FMq3OtLDUKRKssUZwhBqizTu46SSU2HdzuObCrkhYd313nJeTbQGMb4bgadAy+ye9CW5mWgdcQgyQslYrhheg5B9jMNl5iyZfJ+fkE0OQ3ECnpzS34IZPd3Ur1C/nLn2qBT1xCmLn2S159JQu/qdaZ+GDsEFFyowX+oIkqJqk6krbtQQEYvtIjSNf0Lt4bHCJ+BacbUbnH81lWI+H+Ve+A12XABlXYb+xi2BVv1055QvEWoHkHqcWV1e3+v8KG5wtTtIBECEDjdw9OwTF8Dm6J4rZWjNtWeqhEJlYGsJqsC4S1Q9qouTemI5gyt8do1BfjzUJqJsmsE97ciCCEqH78ZSnQef2xCswTtQRQ4yd0XfjkbJmzoZ9uwuvOf8hF4QSlbtqeSI1zZlCE+aCpo+JuoDYp7/A/j90pTcQH5K
  template:
    metadata:
      creationTimestamp: null
      name: auth-secrets
      namespace: turbo-prod
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: google-oauth-secrets
  namespace: turbo-prod
spec:
  encryptedData:
    google-client-id: AgCSQxYQpQVdXXFWx6O/UTFUWBgngkrCw1XuyQBZLwqyj1ot+Sbo6IAP1cLtfPCvq1oKqFTyjL/Kff5yHzUs9pTK54IaN4NfwmdGqb0vwqtIjp0xDYp24O10eBTVNOFt8f47pgizqoiwMBwKrREmWF85whRG5tlkFZMNvCWXw9w86IdNjSPoHjxKDgrglgOsTlcJ8T9qMybrNFvxzCCFeyvFnF/b1VxV4lIp7r/XNUdRhkNb+ilI1w+MLd3FHocESP0LYKCIdXAvbOofOqeBQWbnMFUCmMLgGnX/XOyDwPeeeG+G+FIs/jI3cui3AVbnUF0MjdagdYAm+iMDhV6aWkavAmaHqOP8/hXj9F3syI/GmAdvlXRSpusJEi3jeSI2CkMgfhpIDGsGz270UgBdwyvJTb0SiUWKrR8L6bBClUo+w6fQYALKjP7OFSWWn6QTWhQYDjvwk1ogiceNZxE8wZkUdFkb3TL+kPLW9O3EdJ2UAywmYor3lKZ4sOJMRklhAEvWUcBggVv1Bwq+An1gs98ceDcKZAeAR7cNW8igQOjxAMzN28VtZUx/UE+9HLvec+D4tsnVY49KOz5SZvN+WyZICL9+gtnZ5GTV1l94vE8WyBG9yqU+sl0VLxJ6LEEl1wXrjs84vUhKH4dI53SZRrSCas3EitTK4ttl3+JQl7/C12N7yaJvsNsNLcplhsjqU93Y+UrMvPbMPLX9OgkVidLdpJAd76TKXgHR6k2noUcKqhxLeACjh2uGRUV2eBFWROk/Ug7Xj20ZkkIhteLPkktqY35q4HDmKEQ=
    google-client-secret: AgCUzto8av3aYmhnXOmIpBa+GDPJlxHgqlAr/A/bt9VYrzR/t5yvvvx9pHh02b8Io5wPrQ2OiYM9sNq1nZ9VWZyV5K1+mdCJQDR/un7UA4PsJQ3khzdBibWeKEMf6R7tJE02Hn3B6yq4wwzJhQP7JBdRokJ00h5ss/kX3rg6t1p4FbnqiyqLu1vmZXWrV8dTV77Spxw6CUTZeaEi8FHZFOHRIgR7OpisCDndbYmNMGbla03uOc1ZMmeLFOrgpp51hzRanjEUZSV7W3l+pTcw947Vu9XR6fT5hKwxMaKRbIRITsIDkd+ie42BBIY65I+TiIrWFR+ICp3TMOVRk/rTMxmd8N6HgC3mikOTCLQMpLCZNHyUroS8l1AvlIIL3VmtqDwYSCQj2aMNprd/BhR2qvs/VYIJLc0TaxGG2MyrIvX3aHVRW1pjF8G6zKps2Lxgk1BsA2FLt8L8/pGkbIDf+rhMAwTyIYlcGk5zN8bX9YWUUeP+EjgRTe69ShhKQvotcQhdLguXTy/UTVGOZvmEVFsxp4fkM43q310PJFDy5n8KOL7pmHxMn2D+rivD2JEmCO6o6Yo66krKQp1/gw79k38xvCYF9qW66gr3Zw0flzVRw1RItGxC1hUMCpwxIbLVQUcMuBfymRevAAcPVft6GEVJ6ieedV1sLGi8HnF99wi8LfGakgWKLAsdAkd/At5xkjfHMeZJ7H85/YVzLlRf5ZxJiBVlF2onVTCEaj7CiSDYNXgzXA==
  template:
    metadata:
      creationTimestamp: null
      name: google-oauth-secrets
      namespace: turbo-prod
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-auth
  namespace: turbo-prod
spec:
  encryptedData:
    .dockerconfigjson: AgCn3xMOSyqU/h73UAHZo7nrSWaE5bHS6S37uIfMibk4HMwF6OLiw8RXr50VgnLtaey1dLgxHAHA+VWoUugBchEQO4LMxtmbLQFT6vbkrSCDaLWZb5tq51+GQ2g/ZMnpFu/f5pRJNrSMDB0UA6XY6qX4h8z+6qDvC4Yko18z0KzlIh1K0R1y7QkR9YliCrcPAcKV/gRhIn342IIYe+zPiYut/tiBKpbxlUHQFtTBTKhJr5QEbYPcFPexa4GVO1kW37YaoUriHZUS+3RBQMW33bzHYQjlCaJfubdJOwckwi8mPM8In6Efeh3lUn2qOoe0HgqI6GrCvS2ShbfBXIq6ZBsv9GIRBiHKCmkyWgr8O4pcGpIGQu290+QqMFLWl6PRy/3cijEoPCOPSF9Q/VKJzXCcNtN0rl4LhB+dx5qLcVHGbeMdetK3ONM0K6u5zk4Y45ZQr62TD9dHu1SlXFtf7TS5Y5qXzDUHDEVvoIHWD9WfQ18gw37+Cf9SFzXwTvUKlW5v7xMrC6ytSjkgROH24M5W3k4e2lv7a8paE8wXhjQyr/pgIC44KtLmdLDDJsnLVIbqpEiryVIHuUpxyHHE2VEWaagz6RVUeI7+a2Nrcg2JsDwgmnD/yedg3Nab9yVLguxcm+8SofVxgo+ITrjI4S1VRA+hD4zBcDitnlxVvpLlCIr2fTqDxr2ZPBbjxHYZf0LP/GOXSlKydHaSjAGIbJtBEeqayeZzmbJn5p9oTaCutEYLeaZjXszv78dE4KabjH2WsfTZyg7USsmh7978cZFxVcckreE+EKeIMYSKwsD07F/f9JpdG9/fCo8zUe6prENNqnuaHgMGWGFf81jr2eq9jBLqNZn0HTwRuiSn3NjRNgwDfCeOxlqQlSyD6K7I3TJOwCwmKHOOPrZXVn2ib4sdhh2yTrEPFZfvtrK+E8Fym2Oez70itYqDz22Jcqdxag==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-auth
      namespace: turbo-prod
    type: kubernetes.io/dockerconfigjson
