---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tiles-db-secrets
  namespace: turbo-prod
spec:
  encryptedData:
    connectionstring: AgAWRbn1cIpI9P9oe1t2z2ONUPf9QFjx65atVjIwgmk45/ZaEFdIOcMAwtPtDs2sghBWCiElVFSF6dIYv5TBpu/juFduY/0iIIp2sJ6Ja5l+ffQnBKkgommQEZIOk2r3E7ZImP5/gy+5I9xcnVOCEIi5skOmWWR9B1GklNZETGrBicc0kryjOt0HED+60oGuTCK3Hwrwgqsc8Vdtc9orwxtcVSOESIQSvjnFU9x1xwLWLyvpIA1UHNpEeQB+Gn8u2NLHnbYOXGBGchpLQjqccyQ4MrNWyumw6w76Dfwa9h7LIztnbohul3ssHCb9UgsUfpDySI5GLVZoPmaN8rN+GYahsGOhUSFhSx1YlKCAxY25XxOx/inUJw8p2FyDpbveeGtYWXSTHrk7nmvfg63/wQy1PXlQuszg/abQId2Athiv8ZeX2646TuryW/mj6brCMP1GBcmdPVEGpwdTeANO2WTWB9zhUbQBFUPwz5H8BEKzVn8oxurvz3OVRjRd+fz6iFMIE3W1wneUUB776D6cvN/+YNxGLEwAzqzzmXAlIKjQnJl0LpJtg3F6tSGiPD9dVBpcaS27yUiQvnmDoCgkeoeuDakjGm9mY4jNK2NF62k/nqhjDkjukDbbIN24+FyIlJ5Kkze4bVwmeIRAiNcwkx+4Fx9s6qiVRgM+J4t5SqfZP6QVSZMrHPr/pJOLwcma1qdiPKExmKwY19sDeEL3gNwJsAFdERxa4sF1bArKlBAXowUFsuvmwCjiGeD0tzqnf+dKwJPIjVz64bxye/+gKI9CaiE5zuU2qJEzp/T4nGcgRd6P+pJGUA==
  template:
    metadata:
      name: tiles-db-secrets
      namespace: turbo-prod
