---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tiles-db-app
  namespace: turbo-prod
spec:
  encryptedData:
    password: AgCszd6f8JNAVOLabkRZl44a0JsJiKVshgjIeX6ry8kS0f32r77s1mcJ9z6xXuTlsj/faYnNwGtuZSaTkn5YCqfRh/sDfIiYmMFE3ZEYf/3MpHbWMn+BtC/ZcBM4ynygd5LEXZ3Hhon7TS/NkC4XQiOpq/MwEvkA3l8f6LYjFfKDczUw5QRKK9zZrEDm6i8qJJCqq7LHxYBRh3B1ZqjupJ9Z8A4c/q0i4Waa6Qds0GPIJ4dSJhO0kq3DKw0J87otl09N2hcbvaCZz1e68YYf3zkfZkc1fkjGQSnca5KGU/2XIK6z0smWCOD76C47m/QoJI3KXnYN7VlJZOen168cNV3m73pgmL85jnlRScQUEanjfSxbsu+UClIBzVVOrMhZwLfC5TyRrjsK6mbJhuZtgad4YxPbyYS3ED8wYIAqSaLP4UpjMaKosOh05sZpoTNvs22ZGQPH9ooJ1a4cB3TZj1wQqjOafGPjDujq+s5AcAGsRoU63fm2PTUHfmSRhy/eB58BLLOOB2cFAo33GjsF+QhAFwlKTU2NBcopaokZEwKgKF0Miww0z5IIx2XTnyeGuNFnIWf+k+QrGV1O03hNuL0ZeSa0ZzqFQFRo8/eVqwopKstjZYuxehF+PYtHeJ1JPvXAB6vl0but64Fme4J7qF0XX6b5rW9ocjWSla2QYgk1VzCwG+dzOPYBEWA0TG4RRBCrdkfx2lIUjtG5LE1xpDYeaIWRCjJNSPXQUYSRS4P87hUm4TLr1N6lUEHafQRFgz0=
    username: AgA31qfuF8oSErHbIvJFVrhARclTT0yk9NgyCfDu1PzTsk2dj9zHmABotNv41AR7PfLiOWDvEp0kU9mpZMjeZruAu4Rs6EUWdMoB52awoJu0rFgubTqdCIcMsNzUZhd6CzcY5quZiH0826ByPN15tr0jahT4vTTHwiXElTQAu27YKpofWdHyQZO0GSNe+yQDVvaXCJFKJT29kI5li0yAmH01/Tw4yT3maSEJ8wbuPMuT+oCb+CAlTLMly25uft9fVlEhU4r0hdPUzr4UKof+f5HyMduxAi7b2IvrHtMxeK0UYWzzCzz0VIXzzFuHnrNkpH4a/KtaVokQw9npX329uvQ/SKhmYSP5QE7Wi31X1W8K0z8RK1h1/dRlyKzC+5SGrddYwTu+euSz2UlpIqcqfN+TMUrcnpqfimBdLMrrnrSsJGKWeUJfdM41X5aOrd1LedteFZAsl/pQKqDzFbst5Y4ZzePobCvsyPctKRDlQoCADI+w9ZXSwFZg6TQ898lAQYMuWJQ4NT8fTsmtKcPhoLONdMKIfPPBBaXNP78NriSEgp8Kr4YFZGO8l9ZcH/U191cs69vIGnsFo53VWQmvUV1YI9Zo9P55ZnuKYpDwDYzhW0m48MUjLa4YI1XR4qYsehL1ZiZmGaFf1Ciwvi+Cr6FWyZ41+A84G8PgE+KB7oHLC73lh84vi7a6K79wQDduEkS2Nxs=
  template:
    metadata:
      name: tiles-db-app
      namespace: turbo-prod
    type: kubernetes.io/basic-auth
