---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: turbo-db-app
  namespace: turbo-prod
spec:
  encryptedData:
    password: AgAOiWwWwBoKSMDIORh0de71IFcpEXAp84R1foe/0jzsupTzG5DlbjigLeZeUHr2THOtR3ujI+C423t3iu/Vzf4/YN8neENFgwaFY2MyGzTeXGZ29ojsseZLb59MOViN1ZRJQfzDDEkzPzl2ZpKdTAECTopVV3loCtxBTmnCwwEidod8og8S7qSpXU9V9arKc9S/rHn09t2e0MCUn6NraUAnNF6XL+Vz7XtfkBGR1DkFhcMDMjkmYi4bRM+GIdS8QyorRPs44eB7u9CPCmKgBBR6uzpaAO6HVHJqHbkxJqYEj9+aEQTXwGnbidvbJe16ss1EuEqICVT6Kj6E9NkI5PKjVQ5C5Aw+QjnKGZ3zLFmmd6sG8NOtPF0wXO5Tw/mA/vdsyGBRemB1IloZfLr/L+11/EMCFY2eq6oizKFx+q1kx0B7vDr9cKZLuePC097vwzwmu57uzmmPRHkHCXFu9LX+8DXvmxQKuo4HgFH4KI89hOLpDFHHDpAHVX0Ug4Kf0HjHUPrcZx8UU7aYRLGvTCxsAVJ9D4ADuo//9WYnrdm+y8e+wY0k8D072xJF8s6mnWc478W38ioA5L1zjxf3MgzGuUAu2CuHH5n+ymJTDeV2kXBo8/42IQgUIqdLw2KrDuNBOZ82+yyGhIkCC/yFPtfafeTp6PsjOxO+mVEjes1QJ1fFXMuq8ncA+xfP12RX6zZU3wVMM4/ORIybks15DAWNtGgGZcOr5eGdi7u+lUMKVA==
    username: AgAMbOTw18pGsG0SKNARRKGjkXsPPt/E9UTgEJ5n1QbHCReZjDRG3yQi4coxoe0UVm7GkBPyojzAqRMJaKg4JN5W7bBF9w6rYNyKVk/mqNblF0KlmuqR/+ramBLouIHDIcjHD5xI8Bxy8u0pzMZDz3AFZuaHvycGbpO44epH591KTyWyGpsA3VXmTchMotPSo1V261tk9sPJf7oPVvcL7lOy5Yk+NT9xSwK4BYHMq7sbWKabYfhlb7E7yKNQcLbmBfcMHLwcZOnXNKd57Suo5GjA3oRI1WgYgJFX/VhVI8Oxj15IFO7w+9ZjfOJihbCj44FvU/UyXtTcaaJ3Q2h0jPPw32koF5ZglgDNeVnVEsz4Pmk5AhDyysG7vXNbMlSIAYHzR8XDtRvKaAIm/eDkYlQvIKYkcbKbf/5gL+Cl8Riyi6dxVyzal/y4NO7758PnpFTiOfSf7+ig679ndWSV25NLpgX/WShm1LbcF+AW+M+uOlgE3T3qvYdlCR8YRhgCBRAQjTqGHpXZ/0SfYVtUXmICZ3F5dhtI++kflQnqPxwqEsxYhQrRFFwqhUIhCxIzC0Qi/1BLEFeGI01Qx3ZUsboMa+tzP+8IoCrl+komZGs18ltZZng/0HlbBXZZL2K+LPv6gnGsRxSsZDVEyD1gaqaK2CPWdSLPLk7csSY62Hyt0Z/nGeKsCiHjilZ6UHE5sCIMR8w=
  template:
    metadata:
      creationTimestamp: null
      name: turbo-db-app
      namespace: turbo-prod
    type: kubernetes.io/basic-auth
