

# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

from __future__ import annotations
import os
import sys
import ctypes
import enum
import struct
import contextlib
import datetime
import threading
import itertools
import traceback
import typing
import platform

# Used for default argument values
_DEFAULT = object() # type: typing.Any


class _UniffiRustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_uint64),
        ("len", ctypes.c_uint64),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def default():
        return _UniffiRustBuffer(0, 0, None)

    @staticmethod
    def alloc(size):
        return _uniffi_rust_call(_UniffiLib.ffi_place_core_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return _uniffi_rust_call(_UniffiLib.ffi_place_core_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return _uniffi_rust_call(_UniffiLib.ffi_place_core_rustbuffer_free, self)

    def __str__(self):
        return "_UniffiRustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def alloc_with_builder(*args):
        """Context-manger to allocate a buffer using a _UniffiRustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = _UniffiRustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consume_with_stream(self):
        """Context-manager to consume a buffer using a _UniffiRustBufferStream.

        The _UniffiRustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = _UniffiRustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError("junk data left in buffer at end of consume_with_stream")
        finally:
            self.free()

    @contextlib.contextmanager
    def read_with_stream(self):
        """Context-manager to read a buffer using a _UniffiRustBufferStream.

        This is like consume_with_stream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `_UniffiRustBuffer` data.
        """
        s = _UniffiRustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError("junk data left in buffer at end of read_with_stream")

class _UniffiForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "_UniffiForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class _UniffiRustBufferStream:
    """
    Helper for structured reading of bytes from a _UniffiRustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def read_i8(self):
        return self._unpack_from(1, ">b")

    def read_u8(self):
        return self._unpack_from(1, ">B")

    def read_i16(self):
        return self._unpack_from(2, ">h")

    def read_u16(self):
        return self._unpack_from(2, ">H")

    def read_i32(self):
        return self._unpack_from(4, ">i")

    def read_u32(self):
        return self._unpack_from(4, ">I")

    def read_i64(self):
        return self._unpack_from(8, ">q")

    def read_u64(self):
        return self._unpack_from(8, ">Q")

    def read_float(self):
        v = self._unpack_from(4, ">f")
        return v

    def read_double(self):
        return self._unpack_from(8, ">d")

class _UniffiRustBufferBuilder:
    """
    Helper for structured writing of bytes into a _UniffiRustBuffer.
    """

    def __init__(self):
        self.rbuf = _UniffiRustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, num_bytes):
        if self.rbuf.len + num_bytes > self.rbuf.capacity:
            self.rbuf = _UniffiRustBuffer.reserve(self.rbuf, num_bytes)
        yield None
        self.rbuf.len += num_bytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            # XXX TODO: I feel like I should be able to use `struct.pack_into` here but can't figure it out.
            for i, byte in enumerate(struct.pack(format, value)):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write(self, value):
        with self._reserve(len(value)):
            for i, byte in enumerate(value):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write_i8(self, v):
        self._pack_into(1, ">b", v)

    def write_u8(self, v):
        self._pack_into(1, ">B", v)

    def write_i16(self, v):
        self._pack_into(2, ">h", v)

    def write_u16(self, v):
        self._pack_into(2, ">H", v)

    def write_i32(self, v):
        self._pack_into(4, ">i", v)

    def write_u32(self, v):
        self._pack_into(4, ">I", v)

    def write_i64(self, v):
        self._pack_into(8, ">q", v)

    def write_u64(self, v):
        self._pack_into(8, ">Q", v)

    def write_float(self, v):
        self._pack_into(4, ">f", v)

    def write_double(self, v):
        self._pack_into(8, ">d", v)

    def write_c_size_t(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class _UniffiRustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", _UniffiRustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_UNEXPECTED_ERROR = 2

    @staticmethod
    def default():
        return _UniffiRustCallStatus(code=_UniffiRustCallStatus.CALL_SUCCESS, error_buf=_UniffiRustBuffer.default())

    def __str__(self):
        if self.code == _UniffiRustCallStatus.CALL_SUCCESS:
            return "_UniffiRustCallStatus(CALL_SUCCESS)"
        elif self.code == _UniffiRustCallStatus.CALL_ERROR:
            return "_UniffiRustCallStatus(CALL_ERROR)"
        elif self.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
            return "_UniffiRustCallStatus(CALL_UNEXPECTED_ERROR)"
        else:
            return "_UniffiRustCallStatus(<invalid code>)"

def _uniffi_rust_call(fn, *args):
    # Call a rust function
    return _uniffi_rust_call_with_error(None, fn, *args)

def _uniffi_rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the _UniffiConverter for the error class that corresponds to the result.
    call_status = _UniffiRustCallStatus.default()

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    _uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def _uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == _UniffiRustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == _UniffiRustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("_uniffi_rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
        # When the rust code sees a panic, it tries to construct a _UniffiRustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = _UniffiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid _UniffiRustCallStatus code: {}".format(
            call_status.code))

def _uniffi_trait_interface_call(call_status, make_call, write_return_value):
    try:
        return write_return_value(make_call())
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiConverterString.lower(repr(e))

def _uniffi_trait_interface_call_with_error(call_status, make_call, write_return_value, error_type, lower_error):
    try:
        try:
            return write_return_value(make_call())
        except error_type as e:
            call_status.code = _UniffiRustCallStatus.CALL_ERROR
            call_status.error_buf = lower_error(e)
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiConverterString.lower(repr(e))
class _UniffiHandleMap:
    """
    A map where inserting, getting and removing data is synchronized with a lock.
    """

    def __init__(self):
        # type Handle = int
        self._map = {}  # type: Dict[Handle, Any]
        self._lock = threading.Lock()
        self._counter = itertools.count()

    def insert(self, obj):
        with self._lock:
            handle = next(self._counter)
            self._map[handle] = obj
            return handle

    def get(self, handle):
        try:
            with self._lock:
                return self._map[handle]
        except KeyError:
            raise InternalError("_UniffiHandleMap.get: Invalid handle")

    def remove(self, handle):
        try:
            with self._lock:
                return self._map.pop(handle)
        except KeyError:
            raise InternalError("_UniffiHandleMap.remove: Invalid handle")

    def __len__(self):
        return len(self._map)
# Types conforming to `_UniffiConverterPrimitive` pass themselves directly over the FFI.
class _UniffiConverterPrimitive:
    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return value

class _UniffiConverterPrimitiveInt(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))

class _UniffiConverterPrimitiveFloat(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))

# Helper class for wrapper types that will always go through a _UniffiRustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class _UniffiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consume_with_stream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            cls.write(value, builder)
            return builder.finalize()

# Contains loading, initialization code, and the FFI Function declarations.
# Define some ctypes FFI types that we use in the library

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
_UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int8)

def _uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_uint64, return_type, _UniffiRustCallStatus)

def _uniffi_load_indirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("place_core")
    path = os.path.join(os.path.dirname(__file__), libname)
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def _uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 26
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_place_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def _uniffi_check_api_checksums(lib):
    if lib.uniffi_place_core_checksum_method_placeengine_forward_search() != 27611:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_place_core_checksum_method_placeengine_reverse_geocode() != 17893:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_place_core_checksum_method_placeengine_ruleset_version() != 61736:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_place_core_checksum_constructor_placeengine_from_ruleset_json() != 59077:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_place_core_checksum_constructor_placeengine_with_default_ruleset() != 48803:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniffiLib = _uniffi_load_indirect()
_UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK = ctypes.CFUNCTYPE(None,ctypes.c_uint64,ctypes.c_int8,
)
_UNIFFI_FOREIGN_FUTURE_FREE = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
_UNIFFI_CALLBACK_INTERFACE_FREE = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
class _UniffiForeignFuture(ctypes.Structure):
    _fields_ = [
        ("handle", ctypes.c_uint64),
        ("free", _UNIFFI_FOREIGN_FUTURE_FREE),
    ]
class _UniffiForeignFutureStructU8(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint8),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U8 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU8,
)
class _UniffiForeignFutureStructI8(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int8),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I8 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI8,
)
class _UniffiForeignFutureStructU16(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint16),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U16 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU16,
)
class _UniffiForeignFutureStructI16(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int16),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I16 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI16,
)
class _UniffiForeignFutureStructU32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint32),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU32,
)
class _UniffiForeignFutureStructI32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int32),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI32,
)
class _UniffiForeignFutureStructU64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint64),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU64,
)
class _UniffiForeignFutureStructI64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int64),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI64,
)
class _UniffiForeignFutureStructF32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_float),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_F32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructF32,
)
class _UniffiForeignFutureStructF64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_double),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_F64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructF64,
)
class _UniffiForeignFutureStructPointer(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_void_p),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_POINTER = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructPointer,
)
class _UniffiForeignFutureStructRustBuffer(ctypes.Structure):
    _fields_ = [
        ("return_value", _UniffiRustBuffer),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructRustBuffer,
)
class _UniffiForeignFutureStructVoid(ctypes.Structure):
    _fields_ = [
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_VOID = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructVoid,
)
_UniffiLib.uniffi_place_core_fn_clone_placeengine.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_place_core_fn_clone_placeengine.restype = ctypes.c_void_p
_UniffiLib.uniffi_place_core_fn_free_placeengine.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_place_core_fn_free_placeengine.restype = None
_UniffiLib.uniffi_place_core_fn_constructor_placeengine_from_ruleset_json.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_place_core_fn_constructor_placeengine_from_ruleset_json.restype = ctypes.c_void_p
_UniffiLib.uniffi_place_core_fn_constructor_placeengine_with_default_ruleset.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_place_core_fn_constructor_placeengine_with_default_ruleset.restype = ctypes.c_void_p
_UniffiLib.uniffi_place_core_fn_method_placeengine_forward_search.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_place_core_fn_method_placeengine_forward_search.restype = _UniffiRustBuffer
_UniffiLib.uniffi_place_core_fn_method_placeengine_reverse_geocode.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_place_core_fn_method_placeengine_reverse_geocode.restype = _UniffiRustBuffer
_UniffiLib.uniffi_place_core_fn_method_placeengine_ruleset_version.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_place_core_fn_method_placeengine_ruleset_version.restype = _UniffiRustBuffer
_UniffiLib.ffi_place_core_rustbuffer_alloc.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_place_core_rustbuffer_alloc.restype = _UniffiRustBuffer
_UniffiLib.ffi_place_core_rustbuffer_from_bytes.argtypes = (
    _UniffiForeignBytes,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_place_core_rustbuffer_from_bytes.restype = _UniffiRustBuffer
_UniffiLib.ffi_place_core_rustbuffer_free.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_place_core_rustbuffer_free.restype = None
_UniffiLib.ffi_place_core_rustbuffer_reserve.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_place_core_rustbuffer_reserve.restype = _UniffiRustBuffer
_UniffiLib.ffi_place_core_rust_future_poll_u8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_poll_u8.restype = None
_UniffiLib.ffi_place_core_rust_future_cancel_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_cancel_u8.restype = None
_UniffiLib.ffi_place_core_rust_future_free_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_free_u8.restype = None
_UniffiLib.ffi_place_core_rust_future_complete_u8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_place_core_rust_future_complete_u8.restype = ctypes.c_uint8
_UniffiLib.ffi_place_core_rust_future_poll_i8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_poll_i8.restype = None
_UniffiLib.ffi_place_core_rust_future_cancel_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_cancel_i8.restype = None
_UniffiLib.ffi_place_core_rust_future_free_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_free_i8.restype = None
_UniffiLib.ffi_place_core_rust_future_complete_i8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_place_core_rust_future_complete_i8.restype = ctypes.c_int8
_UniffiLib.ffi_place_core_rust_future_poll_u16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_poll_u16.restype = None
_UniffiLib.ffi_place_core_rust_future_cancel_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_cancel_u16.restype = None
_UniffiLib.ffi_place_core_rust_future_free_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_free_u16.restype = None
_UniffiLib.ffi_place_core_rust_future_complete_u16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_place_core_rust_future_complete_u16.restype = ctypes.c_uint16
_UniffiLib.ffi_place_core_rust_future_poll_i16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_poll_i16.restype = None
_UniffiLib.ffi_place_core_rust_future_cancel_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_cancel_i16.restype = None
_UniffiLib.ffi_place_core_rust_future_free_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_free_i16.restype = None
_UniffiLib.ffi_place_core_rust_future_complete_i16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_place_core_rust_future_complete_i16.restype = ctypes.c_int16
_UniffiLib.ffi_place_core_rust_future_poll_u32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_poll_u32.restype = None
_UniffiLib.ffi_place_core_rust_future_cancel_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_cancel_u32.restype = None
_UniffiLib.ffi_place_core_rust_future_free_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_free_u32.restype = None
_UniffiLib.ffi_place_core_rust_future_complete_u32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_place_core_rust_future_complete_u32.restype = ctypes.c_uint32
_UniffiLib.ffi_place_core_rust_future_poll_i32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_poll_i32.restype = None
_UniffiLib.ffi_place_core_rust_future_cancel_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_cancel_i32.restype = None
_UniffiLib.ffi_place_core_rust_future_free_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_free_i32.restype = None
_UniffiLib.ffi_place_core_rust_future_complete_i32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_place_core_rust_future_complete_i32.restype = ctypes.c_int32
_UniffiLib.ffi_place_core_rust_future_poll_u64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_poll_u64.restype = None
_UniffiLib.ffi_place_core_rust_future_cancel_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_cancel_u64.restype = None
_UniffiLib.ffi_place_core_rust_future_free_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_free_u64.restype = None
_UniffiLib.ffi_place_core_rust_future_complete_u64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_place_core_rust_future_complete_u64.restype = ctypes.c_uint64
_UniffiLib.ffi_place_core_rust_future_poll_i64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_poll_i64.restype = None
_UniffiLib.ffi_place_core_rust_future_cancel_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_cancel_i64.restype = None
_UniffiLib.ffi_place_core_rust_future_free_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_free_i64.restype = None
_UniffiLib.ffi_place_core_rust_future_complete_i64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_place_core_rust_future_complete_i64.restype = ctypes.c_int64
_UniffiLib.ffi_place_core_rust_future_poll_f32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_poll_f32.restype = None
_UniffiLib.ffi_place_core_rust_future_cancel_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_cancel_f32.restype = None
_UniffiLib.ffi_place_core_rust_future_free_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_free_f32.restype = None
_UniffiLib.ffi_place_core_rust_future_complete_f32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_place_core_rust_future_complete_f32.restype = ctypes.c_float
_UniffiLib.ffi_place_core_rust_future_poll_f64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_poll_f64.restype = None
_UniffiLib.ffi_place_core_rust_future_cancel_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_cancel_f64.restype = None
_UniffiLib.ffi_place_core_rust_future_free_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_free_f64.restype = None
_UniffiLib.ffi_place_core_rust_future_complete_f64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_place_core_rust_future_complete_f64.restype = ctypes.c_double
_UniffiLib.ffi_place_core_rust_future_poll_pointer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_poll_pointer.restype = None
_UniffiLib.ffi_place_core_rust_future_cancel_pointer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_cancel_pointer.restype = None
_UniffiLib.ffi_place_core_rust_future_free_pointer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_free_pointer.restype = None
_UniffiLib.ffi_place_core_rust_future_complete_pointer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_place_core_rust_future_complete_pointer.restype = ctypes.c_void_p
_UniffiLib.ffi_place_core_rust_future_poll_rust_buffer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_poll_rust_buffer.restype = None
_UniffiLib.ffi_place_core_rust_future_cancel_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_cancel_rust_buffer.restype = None
_UniffiLib.ffi_place_core_rust_future_free_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_free_rust_buffer.restype = None
_UniffiLib.ffi_place_core_rust_future_complete_rust_buffer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_place_core_rust_future_complete_rust_buffer.restype = _UniffiRustBuffer
_UniffiLib.ffi_place_core_rust_future_poll_void.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_poll_void.restype = None
_UniffiLib.ffi_place_core_rust_future_cancel_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_cancel_void.restype = None
_UniffiLib.ffi_place_core_rust_future_free_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_place_core_rust_future_free_void.restype = None
_UniffiLib.ffi_place_core_rust_future_complete_void.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_place_core_rust_future_complete_void.restype = None
_UniffiLib.uniffi_place_core_checksum_method_placeengine_forward_search.argtypes = (
)
_UniffiLib.uniffi_place_core_checksum_method_placeengine_forward_search.restype = ctypes.c_uint16
_UniffiLib.uniffi_place_core_checksum_method_placeengine_reverse_geocode.argtypes = (
)
_UniffiLib.uniffi_place_core_checksum_method_placeengine_reverse_geocode.restype = ctypes.c_uint16
_UniffiLib.uniffi_place_core_checksum_method_placeengine_ruleset_version.argtypes = (
)
_UniffiLib.uniffi_place_core_checksum_method_placeengine_ruleset_version.restype = ctypes.c_uint16
_UniffiLib.uniffi_place_core_checksum_constructor_placeengine_from_ruleset_json.argtypes = (
)
_UniffiLib.uniffi_place_core_checksum_constructor_placeengine_from_ruleset_json.restype = ctypes.c_uint16
_UniffiLib.uniffi_place_core_checksum_constructor_placeengine_with_default_ruleset.argtypes = (
)
_UniffiLib.uniffi_place_core_checksum_constructor_placeengine_with_default_ruleset.restype = ctypes.c_uint16
_UniffiLib.ffi_place_core_uniffi_contract_version.argtypes = (
)
_UniffiLib.ffi_place_core_uniffi_contract_version.restype = ctypes.c_uint32

_uniffi_check_contract_api_version(_UniffiLib)
# _uniffi_check_api_checksums(_UniffiLib)

# Public interface members begin here.


class _UniffiConverterUInt64(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u64"
    VALUE_MIN = 0
    VALUE_MAX = 2**64

    @staticmethod
    def read(buf):
        return buf.read_u64()

    @staticmethod
    def write(value, buf):
        buf.write_u64(value)

class _UniffiConverterDouble(_UniffiConverterPrimitiveFloat):
    @staticmethod
    def read(buf):
        return buf.read_double()

    @staticmethod
    def write(value, buf):
        buf.write_double(value)

class _UniffiConverterString:
    @staticmethod
    def check_lower(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8_bytes = buf.read(size)
        return utf8_bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        utf8_bytes = value.encode("utf-8")
        buf.write_i32(len(utf8_bytes))
        buf.write(utf8_bytes)

    @staticmethod
    def lift(buf):
        with buf.consume_with_stream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()



class PlaceEngineProtocol(typing.Protocol):
    """
    A reusable engine bound to one ruleset version. Construct once, call many.
    """

    def forward_search(self, query: "str",candidates: "typing.List[SearchCandidate]"):
        """
        Order forward-search candidates for `query` into ranked [`SearchHit`]s.
        """

        raise NotImplementedError
    def reverse_geocode(self, input: "ReverseInput"):
        """
        Reverse-geocode a gathered [`ReverseInput`] to a [`LocationDescription`].
        """

        raise NotImplementedError
    def ruleset_version(self, ):
        """
        The ruleset version this engine is running.
        """

        raise NotImplementedError


class PlaceEngine:
    """
    A reusable engine bound to one ruleset version. Construct once, call many.
    """

    _pointer: ctypes.c_void_p
    
    def __init__(self, *args, **kwargs):
        raise ValueError("This class has no default constructor")

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_place_core_fn_free_placeengine, pointer)

    def _uniffi_clone_pointer(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_place_core_fn_clone_placeengine, self._pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst
    @classmethod
    def from_ruleset_json(cls, json: "str"):
        """
        Engine using a ruleset fetched at runtime (e.g. from
        `GET /api/places/ruleset/{version}` or an offline bundle).
        """

        _UniffiConverterString.check_lower(json)
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = _uniffi_rust_call_with_error(_UniffiConverterTypeEngineError,_UniffiLib.uniffi_place_core_fn_constructor_placeengine_from_ruleset_json,
        _UniffiConverterString.lower(json))
        return cls._make_instance_(pointer)

    @classmethod
    def with_default_ruleset(cls, ):
        """
        Engine using the ruleset embedded in the library (`ruleset.v1.json`).
        """

        # Call the (fallible) function before creating any half-baked object instances.
        pointer = _uniffi_rust_call(_UniffiLib.uniffi_place_core_fn_constructor_placeengine_with_default_ruleset,)
        return cls._make_instance_(pointer)



    def forward_search(self, query: "str",candidates: "typing.List[SearchCandidate]") -> "typing.List[SearchHit]":
        """
        Order forward-search candidates for `query` into ranked [`SearchHit`]s.
        """

        _UniffiConverterString.check_lower(query)
        
        _UniffiConverterSequenceTypeSearchCandidate.check_lower(candidates)
        
        return _UniffiConverterSequenceTypeSearchHit.lift(
            _uniffi_rust_call(_UniffiLib.uniffi_place_core_fn_method_placeengine_forward_search,self._uniffi_clone_pointer(),
        _UniffiConverterString.lower(query),
        _UniffiConverterSequenceTypeSearchCandidate.lower(candidates))
        )





    def reverse_geocode(self, input: "ReverseInput") -> "typing.Optional[LocationDescription]":
        """
        Reverse-geocode a gathered [`ReverseInput`] to a [`LocationDescription`].
        """

        _UniffiConverterTypeReverseInput.check_lower(input)
        
        return _UniffiConverterOptionalTypeLocationDescription.lift(
            _uniffi_rust_call(_UniffiLib.uniffi_place_core_fn_method_placeengine_reverse_geocode,self._uniffi_clone_pointer(),
        _UniffiConverterTypeReverseInput.lower(input))
        )





    def ruleset_version(self, ) -> "str":
        """
        The ruleset version this engine is running.
        """

        return _UniffiConverterString.lift(
            _uniffi_rust_call(_UniffiLib.uniffi_place_core_fn_method_placeengine_ruleset_version,self._uniffi_clone_pointer(),)
        )






class _UniffiConverterTypePlaceEngine:

    @staticmethod
    def lift(value: int):
        return PlaceEngine._make_instance_(value)

    @staticmethod
    def check_lower(value: PlaceEngine):
        if not isinstance(value, PlaceEngine):
            raise TypeError("Expected PlaceEngine instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: PlaceEngineProtocol):
        if not isinstance(value, PlaceEngine):
            raise TypeError("Expected PlaceEngine instance, {} found".format(type(value).__name__))
        return value._uniffi_clone_pointer()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer):
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: PlaceEngineProtocol, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))


class Address:
    """
    Nearest civic address. `text` is the street + number; `secondary` is the
    post code + post town (e.g. "2686 LOM").
    """

    text: "str"
    secondary: "typing.Optional[str]"
    def __init__(self, *, text: "str", secondary: "typing.Optional[str]"):
        self.text = text
        self.secondary = secondary

    def __str__(self):
        return "Address(text={}, secondary={})".format(self.text, self.secondary)

    def __eq__(self, other):
        if self.text != other.text:
            return False
        if self.secondary != other.secondary:
            return False
        return True

class _UniffiConverterTypeAddress(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return Address(
            text=_UniffiConverterString.read(buf),
            secondary=_UniffiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterString.check_lower(value.text)
        _UniffiConverterOptionalString.check_lower(value.secondary)

    @staticmethod
    def write(value, buf):
        _UniffiConverterString.write(value.text, buf)
        _UniffiConverterOptionalString.write(value.secondary, buf)


class Candidate:
    """
    A named toponym candidate (one Stedsnavn `/punkt` row, one PostGIS KNN row,
    or one SQLite R*Tree row). The caller resolves `distance_m` — from the
    server's `meterFraPunkt` when present, else via [`crate::haversine_m`].
    """

    name: "str"
    kind: "str"
    """
    Feature type (`navneobjekttype`), matched case-insensitively against the
    ruleset kind groups.
    """

    distance_m: "float"
    status: "typing.Optional[str]"
    """
    Lifecycle status (`stedstatus`); anything other than the ruleset's
    `active_status` incurs `status_penalty`.
    """

    secondary: "typing.Optional[str]"
    """
    Pre-resolved subtitle, if the source carries one. Reverse-geocode
    (`/punkt`) leaves this `None`; the orchestrator enriches with
    kommune/fylke instead.
    """

    def __init__(self, *, name: "str", kind: "str", distance_m: "float", status: "typing.Optional[str]", secondary: "typing.Optional[str]"):
        self.name = name
        self.kind = kind
        self.distance_m = distance_m
        self.status = status
        self.secondary = secondary

    def __str__(self):
        return "Candidate(name={}, kind={}, distance_m={}, status={}, secondary={})".format(self.name, self.kind, self.distance_m, self.status, self.secondary)

    def __eq__(self, other):
        if self.name != other.name:
            return False
        if self.kind != other.kind:
            return False
        if self.distance_m != other.distance_m:
            return False
        if self.status != other.status:
            return False
        if self.secondary != other.secondary:
            return False
        return True

class _UniffiConverterTypeCandidate(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return Candidate(
            name=_UniffiConverterString.read(buf),
            kind=_UniffiConverterString.read(buf),
            distance_m=_UniffiConverterDouble.read(buf),
            status=_UniffiConverterOptionalString.read(buf),
            secondary=_UniffiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterString.check_lower(value.name)
        _UniffiConverterString.check_lower(value.kind)
        _UniffiConverterDouble.check_lower(value.distance_m)
        _UniffiConverterOptionalString.check_lower(value.status)
        _UniffiConverterOptionalString.check_lower(value.secondary)

    @staticmethod
    def write(value, buf):
        _UniffiConverterString.write(value.name, buf)
        _UniffiConverterString.write(value.kind, buf)
        _UniffiConverterDouble.write(value.distance_m, buf)
        _UniffiConverterOptionalString.write(value.status, buf)
        _UniffiConverterOptionalString.write(value.secondary, buf)


class Kommune:
    """
    The municipality containing the point (final fallback + subtitle context).
    """

    name: "str"
    fylke: "typing.Optional[str]"
    def __init__(self, *, name: "str", fylke: "typing.Optional[str]"):
        self.name = name
        self.fylke = fylke

    def __str__(self):
        return "Kommune(name={}, fylke={})".format(self.name, self.fylke)

    def __eq__(self, other):
        if self.name != other.name:
            return False
        if self.fylke != other.fylke:
            return False
        return True

class _UniffiConverterTypeKommune(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return Kommune(
            name=_UniffiConverterString.read(buf),
            fylke=_UniffiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterString.check_lower(value.name)
        _UniffiConverterOptionalString.check_lower(value.fylke)

    @staticmethod
    def write(value, buf):
        _UniffiConverterString.write(value.name, buf)
        _UniffiConverterOptionalString.write(value.fylke, buf)


class LocationDescription:
    """
    The lenient reverse-geocode result. Mirrors the clients' `LocationDescription`
    field-for-field.
    """

    title: "str"
    qualifier: "typing.Optional[Qualifier]"
    secondary: "typing.Optional[str]"
    kommune: "typing.Optional[str]"
    fylke: "typing.Optional[str]"
    distance_m: "typing.Optional[float]"
    elevation_m: "typing.Optional[float]"
    def __init__(self, *, title: "str", qualifier: "typing.Optional[Qualifier]", secondary: "typing.Optional[str]", kommune: "typing.Optional[str]", fylke: "typing.Optional[str]", distance_m: "typing.Optional[float]", elevation_m: "typing.Optional[float]"):
        self.title = title
        self.qualifier = qualifier
        self.secondary = secondary
        self.kommune = kommune
        self.fylke = fylke
        self.distance_m = distance_m
        self.elevation_m = elevation_m

    def __str__(self):
        return "LocationDescription(title={}, qualifier={}, secondary={}, kommune={}, fylke={}, distance_m={}, elevation_m={})".format(self.title, self.qualifier, self.secondary, self.kommune, self.fylke, self.distance_m, self.elevation_m)

    def __eq__(self, other):
        if self.title != other.title:
            return False
        if self.qualifier != other.qualifier:
            return False
        if self.secondary != other.secondary:
            return False
        if self.kommune != other.kommune:
            return False
        if self.fylke != other.fylke:
            return False
        if self.distance_m != other.distance_m:
            return False
        if self.elevation_m != other.elevation_m:
            return False
        return True

class _UniffiConverterTypeLocationDescription(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return LocationDescription(
            title=_UniffiConverterString.read(buf),
            qualifier=_UniffiConverterOptionalTypeQualifier.read(buf),
            secondary=_UniffiConverterOptionalString.read(buf),
            kommune=_UniffiConverterOptionalString.read(buf),
            fylke=_UniffiConverterOptionalString.read(buf),
            distance_m=_UniffiConverterOptionalDouble.read(buf),
            elevation_m=_UniffiConverterOptionalDouble.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterString.check_lower(value.title)
        _UniffiConverterOptionalTypeQualifier.check_lower(value.qualifier)
        _UniffiConverterOptionalString.check_lower(value.secondary)
        _UniffiConverterOptionalString.check_lower(value.kommune)
        _UniffiConverterOptionalString.check_lower(value.fylke)
        _UniffiConverterOptionalDouble.check_lower(value.distance_m)
        _UniffiConverterOptionalDouble.check_lower(value.elevation_m)

    @staticmethod
    def write(value, buf):
        _UniffiConverterString.write(value.title, buf)
        _UniffiConverterOptionalTypeQualifier.write(value.qualifier, buf)
        _UniffiConverterOptionalString.write(value.secondary, buf)
        _UniffiConverterOptionalString.write(value.kommune, buf)
        _UniffiConverterOptionalString.write(value.fylke, buf)
        _UniffiConverterOptionalDouble.write(value.distance_m, buf)
        _UniffiConverterOptionalDouble.write(value.elevation_m, buf)


class ProtectedArea:
    """
    A containing protected area (national park / nature reserve / …).
    """

    name: "str"
    kind: "typing.Optional[str]"
    """
    Protection class (`verneform`), used as the subtitle.
    """

    def __init__(self, *, name: "str", kind: "typing.Optional[str]"):
        self.name = name
        self.kind = kind

    def __str__(self):
        return "ProtectedArea(name={}, kind={})".format(self.name, self.kind)

    def __eq__(self, other):
        if self.name != other.name:
            return False
        if self.kind != other.kind:
            return False
        return True

class _UniffiConverterTypeProtectedArea(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return ProtectedArea(
            name=_UniffiConverterString.read(buf),
            kind=_UniffiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterString.check_lower(value.name)
        _UniffiConverterOptionalString.check_lower(value.kind)

    @staticmethod
    def write(value, buf):
        _UniffiConverterString.write(value.name, buf)
        _UniffiConverterOptionalString.write(value.kind, buf)


class ReverseInput:
    """
    Everything a platform has gathered for one reverse-geocode. All sources are
    optional; `reverse_geocode` runs the cascade over whatever is present.
    """

    toponyms: "typing.List[Candidate]"
    protected_area: "typing.Optional[ProtectedArea]"
    address: "typing.Optional[Address]"
    kommune: "typing.Optional[Kommune]"
    elevation_m: "typing.Optional[float]"
    """
    Elevation at the queried point; merged onto any winner when finite and
    within the ruleset's `[elevation_min, elevation_max]`.
    """

    def __init__(self, *, toponyms: "typing.List[Candidate]", protected_area: "typing.Optional[ProtectedArea]", address: "typing.Optional[Address]", kommune: "typing.Optional[Kommune]", elevation_m: "typing.Optional[float]"):
        self.toponyms = toponyms
        self.protected_area = protected_area
        self.address = address
        self.kommune = kommune
        self.elevation_m = elevation_m

    def __str__(self):
        return "ReverseInput(toponyms={}, protected_area={}, address={}, kommune={}, elevation_m={})".format(self.toponyms, self.protected_area, self.address, self.kommune, self.elevation_m)

    def __eq__(self, other):
        if self.toponyms != other.toponyms:
            return False
        if self.protected_area != other.protected_area:
            return False
        if self.address != other.address:
            return False
        if self.kommune != other.kommune:
            return False
        if self.elevation_m != other.elevation_m:
            return False
        return True

class _UniffiConverterTypeReverseInput(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return ReverseInput(
            toponyms=_UniffiConverterSequenceTypeCandidate.read(buf),
            protected_area=_UniffiConverterOptionalTypeProtectedArea.read(buf),
            address=_UniffiConverterOptionalTypeAddress.read(buf),
            kommune=_UniffiConverterOptionalTypeKommune.read(buf),
            elevation_m=_UniffiConverterOptionalDouble.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterSequenceTypeCandidate.check_lower(value.toponyms)
        _UniffiConverterOptionalTypeProtectedArea.check_lower(value.protected_area)
        _UniffiConverterOptionalTypeAddress.check_lower(value.address)
        _UniffiConverterOptionalTypeKommune.check_lower(value.kommune)
        _UniffiConverterOptionalDouble.check_lower(value.elevation_m)

    @staticmethod
    def write(value, buf):
        _UniffiConverterSequenceTypeCandidate.write(value.toponyms, buf)
        _UniffiConverterOptionalTypeProtectedArea.write(value.protected_area, buf)
        _UniffiConverterOptionalTypeAddress.write(value.address, buf)
        _UniffiConverterOptionalTypeKommune.write(value.kommune, buf)
        _UniffiConverterOptionalDouble.write(value.elevation_m, buf)


class SearchCandidate:
    """
    One forward-search candidate (a Stedsnavn `/navn` row, a PostGIS trigram
    match, or a local marker/path). The platform resolves `distance_m` from the
    map centre / user location when it wants proximity bias.
    """

    name: "str"
    kind: "str"
    """
    Feature type (`navneobjekttype`), used for the icon.
    """

    distance_m: "typing.Optional[float]"
    """
    Distance from the search origin (map centre), if known. `None` disables
    proximity bias for this candidate (ties fall back to input order).
    """

    description: "typing.Optional[str]"
    """
    Platform-composed subtitle, passed through unchanged.
    """

    def __init__(self, *, name: "str", kind: "str", distance_m: "typing.Optional[float]", description: "typing.Optional[str]"):
        self.name = name
        self.kind = kind
        self.distance_m = distance_m
        self.description = description

    def __str__(self):
        return "SearchCandidate(name={}, kind={}, distance_m={}, description={})".format(self.name, self.kind, self.distance_m, self.description)

    def __eq__(self, other):
        if self.name != other.name:
            return False
        if self.kind != other.kind:
            return False
        if self.distance_m != other.distance_m:
            return False
        if self.description != other.description:
            return False
        return True

class _UniffiConverterTypeSearchCandidate(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return SearchCandidate(
            name=_UniffiConverterString.read(buf),
            kind=_UniffiConverterString.read(buf),
            distance_m=_UniffiConverterOptionalDouble.read(buf),
            description=_UniffiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterString.check_lower(value.name)
        _UniffiConverterString.check_lower(value.kind)
        _UniffiConverterOptionalDouble.check_lower(value.distance_m)
        _UniffiConverterOptionalString.check_lower(value.description)

    @staticmethod
    def write(value, buf):
        _UniffiConverterString.write(value.name, buf)
        _UniffiConverterString.write(value.kind, buf)
        _UniffiConverterOptionalDouble.write(value.distance_m, buf)
        _UniffiConverterOptionalString.write(value.description, buf)


class SearchHit:
    """
    One ranked forward-search result. `index` points back into the input
    candidates so the caller can recover position / source / metadata.
    """

    index: "int"
    title: "str"
    description: "typing.Optional[str]"
    icon: "str"
    def __init__(self, *, index: "int", title: "str", description: "typing.Optional[str]", icon: "str"):
        self.index = index
        self.title = title
        self.description = description
        self.icon = icon

    def __str__(self):
        return "SearchHit(index={}, title={}, description={}, icon={})".format(self.index, self.title, self.description, self.icon)

    def __eq__(self, other):
        if self.index != other.index:
            return False
        if self.title != other.title:
            return False
        if self.description != other.description:
            return False
        if self.icon != other.icon:
            return False
        return True

class _UniffiConverterTypeSearchHit(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return SearchHit(
            index=_UniffiConverterUInt64.read(buf),
            title=_UniffiConverterString.read(buf),
            description=_UniffiConverterOptionalString.read(buf),
            icon=_UniffiConverterString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterUInt64.check_lower(value.index)
        _UniffiConverterString.check_lower(value.title)
        _UniffiConverterOptionalString.check_lower(value.description)
        _UniffiConverterString.check_lower(value.icon)

    @staticmethod
    def write(value, buf):
        _UniffiConverterUInt64.write(value.index, buf)
        _UniffiConverterString.write(value.title, buf)
        _UniffiConverterOptionalString.write(value.description, buf)
        _UniffiConverterString.write(value.icon, buf)


# EngineError
# We want to define each variant as a nested class that's also a subclass,
# which is tricky in Python.  To accomplish this we're going to create each
# class separately, then manually add the child classes to the base class's
# __dict__.  All of this happens in dummy class to avoid polluting the module
# namespace.
class EngineError(Exception):
    """
    Errors surfaced across the FFI boundary.
    """

    pass

_UniffiTempEngineError = EngineError

class EngineError:  # type: ignore
    """
    Errors surfaced across the FFI boundary.
    """

    class InvalidRuleset(_UniffiTempEngineError):
        """
        `from_ruleset_json` was given a ruleset that didn't parse.
        """

        def __init__(self, message):
            super().__init__(", ".join([
                "message={!r}".format(message),
            ]))
            self.message = message

        def __repr__(self):
            return "EngineError.InvalidRuleset({})".format(str(self))
    _UniffiTempEngineError.InvalidRuleset = InvalidRuleset # type: ignore

EngineError = _UniffiTempEngineError # type: ignore
del _UniffiTempEngineError


class _UniffiConverterTypeEngineError(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return EngineError.InvalidRuleset(
                _UniffiConverterString.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if isinstance(value, EngineError.InvalidRuleset):
            _UniffiConverterString.check_lower(value.message)
            return

    @staticmethod
    def write(value, buf):
        if isinstance(value, EngineError.InvalidRuleset):
            buf.write_i32(1)
            _UniffiConverterString.write(value.message, buf)





class Qualifier(enum.Enum):
    """
    Canonical spatial qualifier (the richer Flutter `LocationQualifier` set).
    The Android binding folds `CloseTo`→Near and `InArea`→In to match its
    4-value `PlaceQualifier`; the UI turns these into localized words.
    """

    ON = 0
    """
    Standing on the feature (peak / glacier / island).
    """

    
    CLOSE_TO = 1
    """
    Near but outside a point feature (loose peak / farm / water).
    """

    
    AT_PLACE = 2
    """
    Touching a water body or building.
    """

    
    IN_AREA = 3
    """
    Inside a bounded area (settlement / park).
    """

    
    NEAR = 4
    """
    In the wider periphery of a feature.
    """

    


class _UniffiConverterTypeQualifier(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return Qualifier.ON
        if variant == 2:
            return Qualifier.CLOSE_TO
        if variant == 3:
            return Qualifier.AT_PLACE
        if variant == 4:
            return Qualifier.IN_AREA
        if variant == 5:
            return Qualifier.NEAR
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == Qualifier.ON:
            return
        if value == Qualifier.CLOSE_TO:
            return
        if value == Qualifier.AT_PLACE:
            return
        if value == Qualifier.IN_AREA:
            return
        if value == Qualifier.NEAR:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == Qualifier.ON:
            buf.write_i32(1)
        if value == Qualifier.CLOSE_TO:
            buf.write_i32(2)
        if value == Qualifier.AT_PLACE:
            buf.write_i32(3)
        if value == Qualifier.IN_AREA:
            buf.write_i32(4)
        if value == Qualifier.NEAR:
            buf.write_i32(5)





class _UniffiConverterOptionalDouble(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterDouble.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterDouble.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterDouble.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterOptionalString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterString.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterString.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterString.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterOptionalTypeAddress(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterTypeAddress.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterTypeAddress.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterTypeAddress.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterOptionalTypeKommune(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterTypeKommune.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterTypeKommune.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterTypeKommune.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterOptionalTypeLocationDescription(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterTypeLocationDescription.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterTypeLocationDescription.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterTypeLocationDescription.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterOptionalTypeProtectedArea(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterTypeProtectedArea.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterTypeProtectedArea.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterTypeProtectedArea.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterOptionalTypeQualifier(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterTypeQualifier.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterTypeQualifier.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterTypeQualifier.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterSequenceTypeCandidate(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiConverterTypeCandidate.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiConverterTypeCandidate.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiConverterTypeCandidate.read(buf) for i in range(count)
        ]



class _UniffiConverterSequenceTypeSearchCandidate(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiConverterTypeSearchCandidate.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiConverterTypeSearchCandidate.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiConverterTypeSearchCandidate.read(buf) for i in range(count)
        ]



class _UniffiConverterSequenceTypeSearchHit(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiConverterTypeSearchHit.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiConverterTypeSearchHit.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiConverterTypeSearchHit.read(buf) for i in range(count)
        ]

# Async support

__all__ = [
    "InternalError",
    "EngineError",
    "Qualifier",
    "Address",
    "Candidate",
    "Kommune",
    "LocationDescription",
    "ProtectedArea",
    "ReverseInput",
    "SearchCandidate",
    "SearchHit",
    "PlaceEngine",
]

