// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBELKOpK6tkMRRzcuWw6bjS-Q-W0OnzbeY',
    appId: '1:281611831390:web:6791973c069059bc740ccf',
    messagingSenderId: '281611831390',
    projectId: 'turbo-c1b82',
    authDomain: 'turbo-c1b82.firebaseapp.com',
    storageBucket: 'turbo-c1b82.firebasestorage.app',
    measurementId: 'G-FZ9TCB3J5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGl6pDqvLIQ952YbKNEVZRkMVo7SOBeL0',
    appId: '1:281611831390:android:201745f1aafab1fb740ccf',
    messagingSenderId: '281611831390',
    projectId: 'turbo-c1b82',
    storageBucket: 'turbo-c1b82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpYEDbHYYinu7ZQTeEsR3asl5WtXpj-ak',
    appId: '1:281611831390:ios:3e8c60b4a3f816b3740ccf',
    messagingSenderId: '281611831390',
    projectId: 'turbo-c1b82',
    storageBucket: 'turbo-c1b82.firebasestorage.app',
    iosBundleId: 'com.sigmundgranaas.turbo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpYEDbHYYinu7ZQTeEsR3asl5WtXpj-ak',
    appId: '1:281611831390:ios:3e8c60b4a3f816b3740ccf',
    messagingSenderId: '281611831390',
    projectId: 'turbo-c1b82',
    storageBucket: 'turbo-c1b82.firebasestorage.app',
    iosBundleId: 'com.sigmundgranaas.turbo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBELKOpK6tkMRRzcuWw6bjS-Q-W0OnzbeY',
    appId: '1:281611831390:web:f304ccad5c9f9de1740ccf',
    messagingSenderId: '281611831390',
    projectId: 'turbo-c1b82',
    authDomain: 'turbo-c1b82.firebaseapp.com',
    storageBucket: 'turbo-c1b82.firebasestorage.app',
    measurementId: 'G-CKZMT7588H',
  );

}