#!/usr/bin/env python3
"""Cut the CI corpus out of the full Sjunkhatten corpus.

The full corpus is 90 hikes spread over ~86 x 101 km, and the artifacts
covering it are 209 MB — fine on a workstation, impossible in git. That
means the routing gate only runs where someone has provisioned the data
by hand, so in practice it runs on one machine, occasionally, and the
invariants it protects erode between runs.

This picks the densest cluster of hikes that fits in a small window, so
the pack covering them is small enough to commit and the gate can run on
every push. 25 hikes in ~14 x 15 km slices to 4.6 MB.

Why *densest cluster* rather than "every Nth hike": a scattered sample
would need a pack spanning the whole region, which is the thing being
avoided. Coverage of terrain variety is preserved by the cluster
happening to span all three length buckets (short / mid / long), which
the script reports so a future re-cut can check the same thing.

    python3 tools/make_ci_corpus.py
    cargo run --release -p turbo-tiles-bin --bin tileserver -- slice-pack \\
        --src ~/.data/artifacts --dst tools/ci-pack \\
        --corpus tools/sjunkhatten-ci-corpus.toml
    ./tools/routing_gate.sh ci --update

Re-cutting invalidates the CI baseline. That is expected and fine — but
it must be a deliberate act, not a side effect, so the script never
touches the baseline itself.
"""

import collections
import pathlib
import sys
import tomllib

SRC = pathlib.Path(__file__).parent / "sjunkhatten-corpus.toml"
DST = pathlib.Path(__file__).parent / "sjunkhatten-ci-corpus.toml"

# Window size in degrees, chosen so the sliced pack lands around 5 MB.
# ~13 x 13 km at this latitude. Scanned on a coarse grid; a finer scan
# buys a hike or two and a bigger pack.
WIN_LON, WIN_LAT = 0.30, 0.12
STEP_LON, STEP_LAT = 0.02, 0.01


def main() -> int:
    hikes = tomllib.loads(SRC.read_text())["hike"]
    lons = [c for h in hikes for c in (h["from"][0], h["to"][0])]
    lats = [c for h in hikes for c in (h["from"][1], h["to"][1])]

    # A hike qualifies only if EVERY vertex is inside the window. Testing
    # endpoints alone would admit hikes that bow outside it, and the pack
    # would then be missing terrain the route walks through.
    best = None
    lo = min(lons)
    while lo <= max(lons):
        la = min(lats)
        while la <= max(lats):
            inside = [
                h
                for h in hikes
                if all(
                    lo <= p[0] <= lo + WIN_LON and la <= p[1] <= la + WIN_LAT
                    for p in h["polyline"]
                )
            ]
            if best is None or len(inside) > len(best[0]):
                best = (inside, lo, la)
            la += STEP_LAT
        lo += STEP_LON

    sel, lo, la = best
    if not sel:
        print("no window contained any complete hike", file=sys.stderr)
        return 1

    km = sum(h["length_m"] for h in sel) / 1000
    buckets = collections.Counter(h["region"] for h in sel)
    print(f"window lon={lo:.4f}+{WIN_LON} lat={la:.4f}+{WIN_LAT}")
    print(f"{len(sel)} of {len(hikes)} hikes, {km:.1f} km, buckets: {dict(buckets)}")
    if len(buckets) < 3:
        print(
            "WARNING: the cluster does not span all three length buckets — "
            "the gate will not exercise long routes",
            file=sys.stderr,
        )

    out = [
        "# Sjunkhatten CI corpus — the subset the committed pack covers.",
        "#",
        "# Generated by tools/make_ci_corpus.py: the densest cluster of hikes",
        "# in the full corpus, so the pack covering them is small enough to",
        "# live in git and the routing gate can run on every push.",
        "#",
        "# This corpus has its OWN baseline (tools/sjunkhatten-ci-baseline.json)",
        "# and its hashes are NOT comparable to the full corpus's. The pack is a",
        "# slice: trail edges crossing its boundary are dropped (changing",
        "# trail-proximity bonuses), and defect D8 means dropping a DEM tile can",
        "# change `sample` where tiles overlap. It is a self-consistent",
        "# regression gate, not a cheaper way to compute the same numbers.",
        "#",
        f"# {len(sel)} hikes, {km:.1f} km, buckets: {dict(buckets)}.",
        "",
    ]
    for h in sel:
        out += [
            "[[hike]]",
            f"id = {h['id']}",
            f'region = "{h["region"]}"',
            f"length_m = {h['length_m']}",
            f"from = [{h['from'][0]}, {h['from'][1]}]",
            f"to = [{h['to'][0]}, {h['to'][1]}]",
            "polyline = [",
        ]
        out += [f"  [{p[0]}, {p[1]}]," for p in h["polyline"]]
        out += ["]", ""]

    DST.write_text("\n".join(out))
    print(f"wrote {DST}")
    print("next: slice-pack, then ./tools/routing_gate.sh ci --update")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
