#!/usr/bin/env python3
"""Build the Sjunkhatten ground-truth corpus from the local trail network.

Sjunkhatten is the project's validation region: there is no national
artifact set, so every refactor gate runs against this one 100 km cell.
That makes corpus *size* the binding constraint on how much a green gate
actually proves. The nordland slice of `terrain-corpus.toml` only put 5-6
usable hikes inside the DEM, while the local database holds ~12 000 sti
edges — so the corpus was two orders of magnitude smaller than the data
allows.

Same output shape as `sample_terrain_corpus.py` (`[[hike]]` with id,
region, length_m, from, to, polyline) so `eval-terrain --corpus` consumes
it unchanged. The edge polyline IS the ground truth: a real walked path,
which a terrain-aware solver should re-derive from DEM + landcover.

Selection:
  - `sti` only (fkb_type = 'sti') — walked paths, not roads
  - fully inside the DEM artifact's bbox, with a margin so the corridor
    search is never starved at the edge (E10 measured 500 m as the floor;
    1 km is used here)
  - 300 m - 10 km: below that is an ingest stub, above is usually an
    artefact
  - spread across length buckets and across the region, so the corpus
    exercises short/long and north/south/east/west rather than clustering

Usage:
  DATABASE_URL=postgres://... python3 tools/sample_sjunkhatten_corpus.py [N]
"""
import json
import os
import subprocess
import sys
from pathlib import Path

DB = os.environ.get(
    "DATABASE_URL", "postgres://postgres:testpass@localhost:55433/tiles_sjunkhatten"
)
OUT = Path(__file__).parent / "sjunkhatten-corpus.toml"

# DEM artifact bbox in EPSG:25833, inset by a halo so no hike's corridor
# runs off the edge of coverage. E10: 500 m is the measured floor for
# bit-exact reproduction; 1 km buys margin for longer routes.
DEM = (499795.0, 7399005.0, 585635.0, 7500205.0)
HALO_M = 1000.0
MIN_M, MAX_M = 300.0, 10000.0
N_DEFAULT = 80

# Length buckets, so the corpus is not all 400 m stubs.
BUCKETS = [("short", 300, 800), ("mid", 800, 2000), ("long", 2000, 10000)]


def q(sql: str) -> list:
    r = subprocess.run(
        ["psql", DB, "-tAX", "-c", sql],
        capture_output=True,
        text=True,
        env={**os.environ, "PGPASSWORD": os.environ.get("PGPASSWORD", "testpass")},
    )
    if r.returncode != 0:
        sys.exit(f"psql failed:\n{r.stderr}")
    return [l for l in r.stdout.splitlines() if l.strip()]


def main() -> None:
    n_total = int(sys.argv[1]) if len(sys.argv) > 1 else N_DEFAULT
    minx, miny, maxx, maxy = (
        DEM[0] + HALO_M,
        DEM[1] + HALO_M,
        DEM[2] - HALO_M,
        DEM[3] - HALO_M,
    )
    per_bucket = max(1, n_total // len(BUCKETS))

    hikes = []
    for name, lo, hi in BUCKETS:
        # `ntile` spreads the sample geographically inside the bucket rather
        # than taking the first N, which would clump in one valley.
        sql = f"""
        WITH cands AS (
          SELECT e.id,
                 ST_Length(e.geom) AS len_m,
                 ST_AsGeoJSON(ST_Transform(e.geom, 4326), 6) AS gj,
                 ntile(20) OVER (ORDER BY ST_X(ST_StartPoint(e.geom))) AS xb,
                 ntile(20) OVER (ORDER BY ST_Y(ST_StartPoint(e.geom))) AS yb
          FROM paths.edge e
          WHERE e.fkb_type = 'sti'
            AND ST_Length(e.geom) BETWEEN {lo} AND {hi}
            AND e.geom @ ST_MakeEnvelope({minx},{miny},{maxx},{maxy},25833)
            AND ST_NPoints(e.geom) >= 4
        ), ranked AS (
          SELECT *, row_number() OVER (PARTITION BY xb, yb ORDER BY len_m DESC) AS rn
          FROM cands
        )
        SELECT id, round(len_m::numeric,1), gj
        FROM ranked WHERE rn = 1
        ORDER BY xb, yb
        LIMIT {per_bucket};
        """
        rows = q(sql)
        print(f"  bucket {name:<6} ({lo}-{hi} m): {len(rows)} hikes", file=sys.stderr)
        for line in rows:
            eid, length_m, gj = line.split("|", 2)
            coords = json.loads(gj)["coordinates"]
            if len(coords) < 4:
                continue
            hikes.append(
                {
                    "id": int(eid),
                    "region": f"sjunkhatten-{name}",
                    "length_m": float(length_m),
                    "from": coords[0],
                    "to": coords[-1],
                    "polyline": coords,
                }
            )

    if not hikes:
        sys.exit("no hikes selected — is the DB populated and inside the DEM bbox?")

    with OUT.open("w") as f:
        f.write("# Sjunkhatten ground-truth corpus.\n")
        f.write("# Generated by tools/sample_sjunkhatten_corpus.py from paths.edge.\n")
        f.write("# Each [[hike]] is a real walked `sti` polyline inside the DEM\n")
        f.write("# artifact's coverage, inset by a 1 km halo (see E10).\n")
        f.write(f"# {len(hikes)} hikes.\n")
        for h in hikes:
            f.write("\n[[hike]]\n")
            f.write(f"id = {h['id']}\n")
            f.write(f'region = "{h["region"]}"\n')
            f.write(f"length_m = {h['length_m']}\n")
            f.write(f"from = [{h['from'][0]}, {h['from'][1]}]\n")
            f.write(f"to = [{h['to'][0]}, {h['to'][1]}]\n")
            f.write("polyline = [\n")
            for c in h["polyline"]:
                f.write(f"  [{c[0]}, {c[1]}],\n")
            f.write("]\n")

    tot = sum(h["length_m"] for h in hikes)
    print(f"wrote {OUT} — {len(hikes)} hikes, {tot/1000:.1f} km total", file=sys.stderr)


if __name__ == "__main__":
    main()
