#!/usr/bin/env python3
"""Fail if the shipped Android libraries do not expose the same uniffi
contract as the library the Kotlin bindings were generated from.

# Why this exists

Bindings are generated by loading the *host* cdylib and reading its
metadata; the library that actually ships is cross-compiled for Android.
Nothing checks that those two agree. When they disagree, the app builds,
installs, and then throws

    UniFFI API checksum mismatch: try cleaning and rebuilding your project

on the first FFI call — in front of the user, with a message aimed at a
developer. That shipped once, from a function defined twice under
opposite `cfg`s where only one copy carried a doc comment (uniffi hashes
docstrings into the checksum).

# How

uniffi emits its metadata as `UNIFFI_META_*` statics. Those bytes are the
whole contract — names, signatures, docstrings, everything the checksums
are computed over. Comparing them directly needs no disassembly, so one
implementation covers all three ABIs; the checksum accessors would need
three, being `mov w0` / `movw r0` / `mov eax`.

The ELF reading is done here rather than shelled out to `llvm-readelf` or
`objdump`. Those are not on a stock CI runner — the first version of this
script assumed one was, and the build it was meant to protect failed on
the missing tool instead. A build guard that depends on something the
build does not already require is a guard that fails for the wrong
reason.
"""

from __future__ import annotations

import struct
import sys
from pathlib import Path


class NotElf(Exception):
    """Not an ELF file — a macOS/Windows host cdylib, most likely."""


def _elf_meta_blobs(data: bytes) -> dict[str, bytes]:
    """Every `UNIFFI_META_*` static in an ELF image, by name, as raw bytes.

    Reads the symbol table directly. Release libraries are built with
    `strip = "symbols"`, so `.symtab` is usually gone — but these symbols
    are exported, so `.dynsym` still carries them.
    """
    if data[:4] != b"\x7fELF":
        raise NotElf
    is64 = data[4] == 2
    end = "<" if data[5] == 1 else ">"

    # Section header table: offset, entry size, count, and the index of
    # the section holding section *names*.
    if is64:
        e_shoff, = struct.unpack_from(end + "Q", data, 0x28)
        e_shentsize, e_shnum, e_shstrndx = struct.unpack_from(end + "HHH", data, 0x3A)
    else:
        e_shoff, = struct.unpack_from(end + "I", data, 0x20)
        e_shentsize, e_shnum, e_shstrndx = struct.unpack_from(end + "HHH", data, 0x2E)

    sections = []
    for i in range(e_shnum):
        off = e_shoff + i * e_shentsize
        if is64:
            sh_name, sh_type, _flags, sh_addr, sh_offset, sh_size, sh_link, _info, _align, sh_entsize = \
                struct.unpack_from(end + "IIQQQQIIQQ", data, off)
        else:
            sh_name, sh_type, _flags, sh_addr, sh_offset, sh_size, sh_link, _info, _align, sh_entsize = \
                struct.unpack_from(end + "IIIIIIIIII", data, off)
        sections.append(dict(
            name=sh_name, type=sh_type, addr=sh_addr, offset=sh_offset,
            size=sh_size, link=sh_link, entsize=sh_entsize,
        ))

    def cstr(base: int, at: int) -> str:
        stop = data.index(b"\0", base + at)
        return data[base + at:stop].decode("utf-8", "replace")

    # A virtual address only tells us where the loader puts the bytes;
    # to read them out of the file we need the section that contains it.
    def vaddr_to_offset(vaddr: int) -> int | None:
        for s in sections:
            if s["type"] != 8 and s["addr"] and s["addr"] <= vaddr < s["addr"] + s["size"]:
                return s["offset"] + (vaddr - s["addr"])
        return None

    blobs: dict[str, bytes] = {}
    SHT_SYMTAB, SHT_DYNSYM = 2, 11
    for s in sections:
        if s["type"] not in (SHT_SYMTAB, SHT_DYNSYM) or not s["entsize"]:
            continue
        strtab = sections[s["link"]]["offset"]
        for i in range(s["size"] // s["entsize"]):
            off = s["offset"] + i * s["entsize"]
            if is64:
                st_name, _info, _other, _shndx, st_value, st_size = \
                    struct.unpack_from(end + "IBBHQQ", data, off)
            else:
                st_name, st_value, st_size, _info, _other, _shndx = \
                    struct.unpack_from(end + "IIIBBH", data, off)
            if not st_name or not st_size:
                continue
            name = cstr(strtab, st_name)
            if not name.startswith("UNIFFI_META_") or name in blobs:
                continue
            start = vaddr_to_offset(st_value)
            if start is not None:
                blobs[name] = data[start:start + st_size]
    return blobs


def meta_blobs(lib: Path) -> dict[str, bytes]:
    blobs = _elf_meta_blobs(lib.read_bytes())
    if not blobs:
        sys.exit(f"{lib}: no UNIFFI_META_* symbols — is this the right library?")
    return blobs


def main() -> int:
    if len(sys.argv) < 3:
        print(f"usage: {sys.argv[0]} <host-lib> <android-lib>...", file=sys.stderr)
        return 2
    host, *targets = (Path(p) for p in sys.argv[1:])

    try:
        reference = meta_blobs(host)
    except NotElf:
        # The Android libraries are always ELF; the host cdylib is a
        # Mach-O dylib on macOS and a PE DLL on Windows. Rather than ship
        # an untested reader for formats this cannot be tested against,
        # say plainly that the check did not run. CI is Linux, so the
        # gate that blocks a merge is never the one being skipped here.
        print(f"verify-ffi-abi: {host.name} is not ELF — skipping on this host.")
        print("verify-ffi-abi: the Linux CI run is what enforces this; a mismatch")
        print("verify-ffi-abi: introduced here will be caught there, not now.")
        return 0

    failed = False
    for lib in targets:
        got = meta_blobs(lib)
        # Sort so the report is stable and reads as a diff.
        for name in sorted(set(reference) | set(got)):
            a, b = reference.get(name), got.get(name)
            if a == b:
                continue
            failed = True
            if a is None:
                print(f"{lib}: exports {name}, which {host} does not")
            elif b is None:
                print(f"{lib}: is missing {name}, which the bindings expect")
            else:
                # Window on the first difference, not on the start of the
                # blob. These begin with the module path and function
                # name, which are identical in every interesting case —
                # a fixed prefix would print the same bytes twice and
                # hide the divergence somewhere off the right edge.
                at = next(
                    (i for i in range(min(len(a), len(b))) if a[i] != b[i]),
                    min(len(a), len(b)),
                )
                lo = max(0, at - 8)
                print(f"{lib}: {name} differs from the bindings' copy, at byte {at}")
                print(f"    bindings: …{a[lo:at + 40].hex()}")
                print(f"    shipped : …{b[lo:at + 40].hex()}")
                # The readable half: these blobs are mostly UTF-8 (names,
                # docstrings), and the text is usually the whole answer.
                for label, blob in (("bindings", a), ("shipped ", b)):
                    txt = "".join(chr(c) if 32 <= c < 127 else "." for c in blob[lo:at + 40])
                    print(f"    {label}: {txt}")

    if failed:
        print()
        print("The Kotlin bindings were generated from a library with a different")
        print("uniffi contract than the one being packaged. This ships as a runtime")
        print("'UniFFI API checksum mismatch' on the user's phone, not a build error.")
        print()
        print("The usual cause is a #[uniffi::export] item defined more than once")
        print("under differing cfgs — target_os, or a feature that is on for one")
        print("build and not the other. Put the cfg inside the body instead, so the")
        print("exported signature and its docstring are the same on every target.")
        return 1

    print(f"uniffi contract matches across {len(targets)} ABI(s): "
          f"{len(reference)} metadata items identical")
    return 0


if __name__ == "__main__":
    sys.exit(main())
