#!/usr/bin/env python3
"""Fail if the shipped Android libraries do not expose the same uniffi
contract as the library the Kotlin bindings were generated from.

# Why this exists

Bindings are generated by loading the *host* cdylib and reading its
metadata; the library that actually ships is cross-compiled for Android.
Nothing checks that those two agree. When they disagree, the app builds,
installs, and then throws

    UniFFI API checksum mismatch: try cleaning and rebuilding your project

on the first FFI call — in front of the user, with a message aimed at a
developer. That shipped once, from a function defined twice under
opposite `cfg`s where only one copy carried a doc comment (uniffi hashes
docstrings into the checksum).

# How

uniffi emits its metadata as `UNIFFI_META_*` statics in `.rodata`. Those
bytes are the whole contract — names, signatures, docstrings, everything
the checksums are computed over. Comparing them directly needs no
disassembly and so is identical across ABIs, which the checksum
accessors (`mov w0` / `movw r0` / `mov eax`) are not.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


def meta_blobs(lib: Path) -> dict[str, bytes]:
    """Every `UNIFFI_META_*` static in `lib`, by name, as raw bytes."""
    out = subprocess.run(
        ["llvm-readelf", "--symbols", "--wide", str(lib)],
        capture_output=True, text=True, check=True,
    ).stdout

    # Value Size ... Name — we want the address and length of each blob.
    wanted: dict[str, tuple[int, int]] = {}
    for line in out.splitlines():
        parts = line.split()
        if len(parts) < 8 or not parts[-1].startswith("UNIFFI_META_"):
            continue
        try:
            addr, size = int(parts[1], 16), int(parts[2], 0)
        except ValueError:
            continue
        if size:
            wanted[parts[-1]] = (addr, size)
    if not wanted:
        sys.exit(f"{lib}: no UNIFFI_META_* symbols — is this the right library?")

    # One pass over the file. Section headers give us the vaddr->offset map.
    sections = []
    for line in subprocess.run(
        ["llvm-readelf", "--section-headers", "--wide", str(lib)],
        capture_output=True, text=True, check=True,
    ).stdout.splitlines():
        parts = line.split()
        # [Nr] Name Type Address Off Size ...
        if len(parts) >= 7 and parts[0].startswith("[") and parts[2] == "PROGBITS":
            try:
                sections.append((int(parts[3], 16), int(parts[4], 16), int(parts[5], 16)))
            except ValueError:
                continue

    data = lib.read_bytes()
    blobs: dict[str, bytes] = {}
    for name, (addr, size) in wanted.items():
        for vaddr, off, sz in sections:
            if vaddr <= addr < vaddr + sz:
                start = off + (addr - vaddr)
                blobs[name] = data[start:start + size]
                break
        else:
            sys.exit(f"{lib}: {name} at {addr:#x} is in no PROGBITS section")
    return blobs


def main() -> int:
    if len(sys.argv) < 3:
        return int(bool(sys.exit(f"usage: {sys.argv[0]} <host-lib> <android-lib>...")))
    host, *targets = (Path(p) for p in sys.argv[1:])
    reference = meta_blobs(host)

    failed = False
    for lib in targets:
        got = meta_blobs(lib)
        # Sort so the report is stable and reads as a diff.
        for name in sorted(set(reference) | set(got)):
            a, b = reference.get(name), got.get(name)
            if a == b:
                continue
            failed = True
            if a is None:
                print(f"{lib}: exports {name}, which {host} does not")
            elif b is None:
                print(f"{lib}: is missing {name}, which the bindings expect")
            else:
                print(f"{lib}: {name} differs from the bindings' copy")
                print(f"    bindings: {a[:96].hex()}")
                print(f"    shipped : {b[:96].hex()}")

    if failed:
        print()
        print("The Kotlin bindings were generated from a library with a different")
        print("uniffi contract than the one being packaged. This ships as a runtime")
        print("'UniFFI API checksum mismatch' on the user's phone, not a build error.")
        print()
        print("The usual cause is a #[uniffi::export] item defined more than once")
        print("under differing cfgs — target_os, or a feature that is on for one")
        print("build and not the other. Put the cfg inside the body instead, so the")
        print("exported signature and its docstring are the same on every target.")
        return 1

    print(f"uniffi contract matches across {len(targets)} ABI(s): "
          f"{len(reference)} metadata items identical")
    return 0


if __name__ == "__main__":
    sys.exit(main())
