apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config.yaml
  - db.yaml
  - modulith.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: turboapi
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
