// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Turboapi.Activities.data;

#nullable disable

namespace Turboapi.Activities.data.Migrations
{
    [DbContext(typeof(ActivitySummariesContext))]
    [Migration("20260524075438_AddOrchestratorFoundations")]
    partial class AddOrchestratorFoundations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Turbo.Outbox.Postgres.OutboxRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("DataContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_content_type");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("headers_json");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<long>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("position");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Position"));

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId", "Position")
                        .HasDatabaseName("outbox_aggregate");

                    b.HasIndex("DispatchedAt", "Position")
                        .HasDatabaseName("outbox_undispatched")
                        .HasFilter("dispatched_at IS NULL");

                    b.ToTable("outbox", "activities");
                });

            modelBuilder.Entity("Turbo.Outbox.Postgres.ProcessedEventRow", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("ProcessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("EventId");

                    b.ToTable("processed_events", "activities");
                });

            modelBuilder.Entity("Turboapi.Activities.data.model.ActivityGeoContextEntity", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<string>("GeomHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("geom_hash");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("ActivityId");

                    b.ToTable("activity_geo_contexts", "activities");
                });

            modelBuilder.Entity("Turboapi.Activities.data.model.ActivityObservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<JsonDocument>("KindPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("kind_payload");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<short>("PhotoCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("photo_count");

                    b.Property<short?>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WatershedHrefId")
                        .HasColumnType("text")
                        .HasColumnName("watershed_href_id");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "ObservedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_activity_observations_activity_observed_at");

                    b.HasIndex("WatershedHrefId", "ObservedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_activity_observations_watershed_observed_at");

                    b.HasIndex("UserId", "Kind", "ObservedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("idx_activity_observations_user_kind_observed_at");

                    b.ToTable("activity_observations", "activities");
                });

            modelBuilder.Entity("Turboapi.Activities.data.model.ActivitySummaryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ColorHex")
                        .HasColumnType("text")
                        .HasColumnName("color_hex");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry, 4326)")
                        .HasColumnName("geometry");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon_key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Geometry")
                        .HasDatabaseName("idx_activity_summaries_geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "GIST");

                    b.HasIndex("Kind")
                        .HasDatabaseName("idx_activity_summaries_kind");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("idx_activity_summaries_owner");

                    b.HasIndex("OwnerId", "UpdatedAt")
                        .HasDatabaseName("idx_activity_summaries_owner_updated_at");

                    b.ToTable("activity_summaries", "activities");
                });

            modelBuilder.Entity("Turboapi.Activities.data.model.ActivityVisitEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visited_at");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "VisitedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_activity_visits_activity_visited_at");

                    b.HasIndex("UserId", "VisitedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_activity_visits_user_visited_at");

                    b.ToTable("activity_visits", "activities");
                });

            modelBuilder.Entity("Turboapi.Activities.data.model.ConditionsCacheEntity", b =>
                {
                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("GridCell")
                        .HasColumnType("text")
                        .HasColumnName("grid_cell");

                    b.Property<DateTime>("TimeBucket")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_bucket");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload");

                    b.HasKey("ProviderKey", "GridCell", "TimeBucket");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_conditions_cache_expires_at");

                    b.ToTable("conditions_cache", "activities");
                });

            modelBuilder.Entity("Turboapi.Activities.data.model.ConditionsSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("GridCell")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grid_cell");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.PrimitiveCollection<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<short>("PayloadSchemaVersion")
                        .HasColumnType("smallint")
                        .HasColumnName("payload_schema_version");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.HasKey("Id");

                    b.HasIndex("ProviderKey", "GridCell", "ObservedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("idx_conditions_snapshots_provider_grid_observed_at");

                    b.ToTable("conditions_snapshots", "activities");
                });
#pragma warning restore 612, 618
        }
    }
}
