// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(place_coreFFI)
import place_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_place_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_place_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * A reusable engine bound to one ruleset version. Construct once, call many.
 */
public protocol PlaceEngineProtocol : AnyObject {
    
    /**
     * Order forward-search candidates for `query` into ranked [`SearchHit`]s.
     */
    func forwardSearch(query: String, candidates: [SearchCandidate])  -> [SearchHit]
    
    /**
     * Reverse-geocode a gathered [`ReverseInput`] to a [`LocationDescription`].
     */
    func reverseGeocode(input: ReverseInput)  -> LocationDescription?
    
    /**
     * The ruleset version this engine is running.
     */
    func rulesetVersion()  -> String
    
}

/**
 * A reusable engine bound to one ruleset version. Construct once, call many.
 */
open class PlaceEngine:
    PlaceEngineProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_place_core_fn_clone_placeengine(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_place_core_fn_free_placeengine(pointer, $0) }
    }

    
    /**
     * Engine using a ruleset fetched at runtime (e.g. from
     * `GET /api/places/ruleset/{version}` or an offline bundle).
     */
public static func fromRulesetJson(json: String)throws  -> PlaceEngine {
    return try  FfiConverterTypePlaceEngine.lift(try rustCallWithError(FfiConverterTypeEngineError.lift) {
    uniffi_place_core_fn_constructor_placeengine_from_ruleset_json(
        FfiConverterString.lower(json),$0
    )
})
}
    
    /**
     * Engine using the ruleset embedded in the library (`ruleset.v1.json`).
     */
public static func withDefaultRuleset() -> PlaceEngine {
    return try!  FfiConverterTypePlaceEngine.lift(try! rustCall() {
    uniffi_place_core_fn_constructor_placeengine_with_default_ruleset($0
    )
})
}
    

    
    /**
     * Order forward-search candidates for `query` into ranked [`SearchHit`]s.
     */
open func forwardSearch(query: String, candidates: [SearchCandidate]) -> [SearchHit] {
    return try!  FfiConverterSequenceTypeSearchHit.lift(try! rustCall() {
    uniffi_place_core_fn_method_placeengine_forward_search(self.uniffiClonePointer(),
        FfiConverterString.lower(query),
        FfiConverterSequenceTypeSearchCandidate.lower(candidates),$0
    )
})
}
    
    /**
     * Reverse-geocode a gathered [`ReverseInput`] to a [`LocationDescription`].
     */
open func reverseGeocode(input: ReverseInput) -> LocationDescription? {
    return try!  FfiConverterOptionTypeLocationDescription.lift(try! rustCall() {
    uniffi_place_core_fn_method_placeengine_reverse_geocode(self.uniffiClonePointer(),
        FfiConverterTypeReverseInput.lower(input),$0
    )
})
}
    
    /**
     * The ruleset version this engine is running.
     */
open func rulesetVersion() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_place_core_fn_method_placeengine_ruleset_version(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePlaceEngine: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = PlaceEngine

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> PlaceEngine {
        return PlaceEngine(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: PlaceEngine) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PlaceEngine {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: PlaceEngine, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlaceEngine_lift(_ pointer: UnsafeMutableRawPointer) throws -> PlaceEngine {
    return try FfiConverterTypePlaceEngine.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlaceEngine_lower(_ value: PlaceEngine) -> UnsafeMutableRawPointer {
    return FfiConverterTypePlaceEngine.lower(value)
}


/**
 * Nearest civic address. `text` is the street + number; `secondary` is the
 * post code + post town (e.g. "2686 LOM").
 */
public struct Address {
    public var text: String
    public var secondary: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(text: String, secondary: String?) {
        self.text = text
        self.secondary = secondary
    }
}



extension Address: Equatable, Hashable {
    public static func ==(lhs: Address, rhs: Address) -> Bool {
        if lhs.text != rhs.text {
            return false
        }
        if lhs.secondary != rhs.secondary {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(text)
        hasher.combine(secondary)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAddress: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Address {
        return
            try Address(
                text: FfiConverterString.read(from: &buf), 
                secondary: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: Address, into buf: inout [UInt8]) {
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterOptionString.write(value.secondary, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAddress_lift(_ buf: RustBuffer) throws -> Address {
    return try FfiConverterTypeAddress.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAddress_lower(_ value: Address) -> RustBuffer {
    return FfiConverterTypeAddress.lower(value)
}


/**
 * A named toponym candidate (one Stedsnavn `/punkt` row, one PostGIS KNN row,
 * or one SQLite R*Tree row). The caller resolves `distance_m` — from the
 * server's `meterFraPunkt` when present, else via [`crate::haversine_m`].
 */
public struct Candidate {
    public var name: String
    /**
     * Feature type (`navneobjekttype`), matched case-insensitively against the
     * ruleset kind groups.
     */
    public var kind: String
    public var distanceM: Double
    /**
     * Lifecycle status (`stedstatus`); anything other than the ruleset's
     * `active_status` incurs `status_penalty`.
     */
    public var status: String?
    /**
     * Pre-resolved subtitle, if the source carries one. Reverse-geocode
     * (`/punkt`) leaves this `None`; the orchestrator enriches with
     * kommune/fylke instead.
     */
    public var secondary: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, 
        /**
         * Feature type (`navneobjekttype`), matched case-insensitively against the
         * ruleset kind groups.
         */kind: String, distanceM: Double, 
        /**
         * Lifecycle status (`stedstatus`); anything other than the ruleset's
         * `active_status` incurs `status_penalty`.
         */status: String?, 
        /**
         * Pre-resolved subtitle, if the source carries one. Reverse-geocode
         * (`/punkt`) leaves this `None`; the orchestrator enriches with
         * kommune/fylke instead.
         */secondary: String?) {
        self.name = name
        self.kind = kind
        self.distanceM = distanceM
        self.status = status
        self.secondary = secondary
    }
}



extension Candidate: Equatable, Hashable {
    public static func ==(lhs: Candidate, rhs: Candidate) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.distanceM != rhs.distanceM {
            return false
        }
        if lhs.status != rhs.status {
            return false
        }
        if lhs.secondary != rhs.secondary {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(kind)
        hasher.combine(distanceM)
        hasher.combine(status)
        hasher.combine(secondary)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCandidate: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Candidate {
        return
            try Candidate(
                name: FfiConverterString.read(from: &buf), 
                kind: FfiConverterString.read(from: &buf), 
                distanceM: FfiConverterDouble.read(from: &buf), 
                status: FfiConverterOptionString.read(from: &buf), 
                secondary: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: Candidate, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.kind, into: &buf)
        FfiConverterDouble.write(value.distanceM, into: &buf)
        FfiConverterOptionString.write(value.status, into: &buf)
        FfiConverterOptionString.write(value.secondary, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCandidate_lift(_ buf: RustBuffer) throws -> Candidate {
    return try FfiConverterTypeCandidate.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCandidate_lower(_ value: Candidate) -> RustBuffer {
    return FfiConverterTypeCandidate.lower(value)
}


/**
 * The municipality containing the point (final fallback + subtitle context).
 */
public struct Kommune {
    public var name: String
    public var fylke: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, fylke: String?) {
        self.name = name
        self.fylke = fylke
    }
}



extension Kommune: Equatable, Hashable {
    public static func ==(lhs: Kommune, rhs: Kommune) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.fylke != rhs.fylke {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(fylke)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeKommune: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Kommune {
        return
            try Kommune(
                name: FfiConverterString.read(from: &buf), 
                fylke: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: Kommune, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.fylke, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKommune_lift(_ buf: RustBuffer) throws -> Kommune {
    return try FfiConverterTypeKommune.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKommune_lower(_ value: Kommune) -> RustBuffer {
    return FfiConverterTypeKommune.lower(value)
}


/**
 * The lenient reverse-geocode result. Mirrors the clients' `LocationDescription`
 * field-for-field.
 */
public struct LocationDescription {
    public var title: String
    public var qualifier: Qualifier?
    public var secondary: String?
    public var kommune: String?
    public var fylke: String?
    public var distanceM: Double?
    public var elevationM: Double?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(title: String, qualifier: Qualifier?, secondary: String?, kommune: String?, fylke: String?, distanceM: Double?, elevationM: Double?) {
        self.title = title
        self.qualifier = qualifier
        self.secondary = secondary
        self.kommune = kommune
        self.fylke = fylke
        self.distanceM = distanceM
        self.elevationM = elevationM
    }
}



extension LocationDescription: Equatable, Hashable {
    public static func ==(lhs: LocationDescription, rhs: LocationDescription) -> Bool {
        if lhs.title != rhs.title {
            return false
        }
        if lhs.qualifier != rhs.qualifier {
            return false
        }
        if lhs.secondary != rhs.secondary {
            return false
        }
        if lhs.kommune != rhs.kommune {
            return false
        }
        if lhs.fylke != rhs.fylke {
            return false
        }
        if lhs.distanceM != rhs.distanceM {
            return false
        }
        if lhs.elevationM != rhs.elevationM {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(title)
        hasher.combine(qualifier)
        hasher.combine(secondary)
        hasher.combine(kommune)
        hasher.combine(fylke)
        hasher.combine(distanceM)
        hasher.combine(elevationM)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLocationDescription: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LocationDescription {
        return
            try LocationDescription(
                title: FfiConverterString.read(from: &buf), 
                qualifier: FfiConverterOptionTypeQualifier.read(from: &buf), 
                secondary: FfiConverterOptionString.read(from: &buf), 
                kommune: FfiConverterOptionString.read(from: &buf), 
                fylke: FfiConverterOptionString.read(from: &buf), 
                distanceM: FfiConverterOptionDouble.read(from: &buf), 
                elevationM: FfiConverterOptionDouble.read(from: &buf)
        )
    }

    public static func write(_ value: LocationDescription, into buf: inout [UInt8]) {
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterOptionTypeQualifier.write(value.qualifier, into: &buf)
        FfiConverterOptionString.write(value.secondary, into: &buf)
        FfiConverterOptionString.write(value.kommune, into: &buf)
        FfiConverterOptionString.write(value.fylke, into: &buf)
        FfiConverterOptionDouble.write(value.distanceM, into: &buf)
        FfiConverterOptionDouble.write(value.elevationM, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLocationDescription_lift(_ buf: RustBuffer) throws -> LocationDescription {
    return try FfiConverterTypeLocationDescription.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLocationDescription_lower(_ value: LocationDescription) -> RustBuffer {
    return FfiConverterTypeLocationDescription.lower(value)
}


/**
 * A containing protected area (national park / nature reserve / …).
 */
public struct ProtectedArea {
    public var name: String
    /**
     * Protection class (`verneform`), used as the subtitle.
     */
    public var kind: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, 
        /**
         * Protection class (`verneform`), used as the subtitle.
         */kind: String?) {
        self.name = name
        self.kind = kind
    }
}



extension ProtectedArea: Equatable, Hashable {
    public static func ==(lhs: ProtectedArea, rhs: ProtectedArea) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.kind != rhs.kind {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(kind)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProtectedArea: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProtectedArea {
        return
            try ProtectedArea(
                name: FfiConverterString.read(from: &buf), 
                kind: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: ProtectedArea, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.kind, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProtectedArea_lift(_ buf: RustBuffer) throws -> ProtectedArea {
    return try FfiConverterTypeProtectedArea.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProtectedArea_lower(_ value: ProtectedArea) -> RustBuffer {
    return FfiConverterTypeProtectedArea.lower(value)
}


/**
 * Everything a platform has gathered for one reverse-geocode. All sources are
 * optional; `reverse_geocode` runs the cascade over whatever is present.
 */
public struct ReverseInput {
    public var toponyms: [Candidate]
    public var protectedArea: ProtectedArea?
    public var address: Address?
    public var kommune: Kommune?
    /**
     * Elevation at the queried point; merged onto any winner when finite and
     * within the ruleset's `[elevation_min, elevation_max]`.
     */
    public var elevationM: Double?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(toponyms: [Candidate], protectedArea: ProtectedArea?, address: Address?, kommune: Kommune?, 
        /**
         * Elevation at the queried point; merged onto any winner when finite and
         * within the ruleset's `[elevation_min, elevation_max]`.
         */elevationM: Double?) {
        self.toponyms = toponyms
        self.protectedArea = protectedArea
        self.address = address
        self.kommune = kommune
        self.elevationM = elevationM
    }
}



extension ReverseInput: Equatable, Hashable {
    public static func ==(lhs: ReverseInput, rhs: ReverseInput) -> Bool {
        if lhs.toponyms != rhs.toponyms {
            return false
        }
        if lhs.protectedArea != rhs.protectedArea {
            return false
        }
        if lhs.address != rhs.address {
            return false
        }
        if lhs.kommune != rhs.kommune {
            return false
        }
        if lhs.elevationM != rhs.elevationM {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(toponyms)
        hasher.combine(protectedArea)
        hasher.combine(address)
        hasher.combine(kommune)
        hasher.combine(elevationM)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeReverseInput: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ReverseInput {
        return
            try ReverseInput(
                toponyms: FfiConverterSequenceTypeCandidate.read(from: &buf), 
                protectedArea: FfiConverterOptionTypeProtectedArea.read(from: &buf), 
                address: FfiConverterOptionTypeAddress.read(from: &buf), 
                kommune: FfiConverterOptionTypeKommune.read(from: &buf), 
                elevationM: FfiConverterOptionDouble.read(from: &buf)
        )
    }

    public static func write(_ value: ReverseInput, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeCandidate.write(value.toponyms, into: &buf)
        FfiConverterOptionTypeProtectedArea.write(value.protectedArea, into: &buf)
        FfiConverterOptionTypeAddress.write(value.address, into: &buf)
        FfiConverterOptionTypeKommune.write(value.kommune, into: &buf)
        FfiConverterOptionDouble.write(value.elevationM, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReverseInput_lift(_ buf: RustBuffer) throws -> ReverseInput {
    return try FfiConverterTypeReverseInput.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReverseInput_lower(_ value: ReverseInput) -> RustBuffer {
    return FfiConverterTypeReverseInput.lower(value)
}


/**
 * One forward-search candidate (a Stedsnavn `/navn` row, a PostGIS trigram
 * match, or a local marker/path). The platform resolves `distance_m` from the
 * map centre / user location when it wants proximity bias.
 */
public struct SearchCandidate {
    public var name: String
    /**
     * Feature type (`navneobjekttype`), used for the icon.
     */
    public var kind: String
    /**
     * Distance from the search origin (map centre), if known. `None` disables
     * proximity bias for this candidate (ties fall back to input order).
     */
    public var distanceM: Double?
    /**
     * Platform-composed subtitle, passed through unchanged.
     */
    public var description: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, 
        /**
         * Feature type (`navneobjekttype`), used for the icon.
         */kind: String, 
        /**
         * Distance from the search origin (map centre), if known. `None` disables
         * proximity bias for this candidate (ties fall back to input order).
         */distanceM: Double?, 
        /**
         * Platform-composed subtitle, passed through unchanged.
         */description: String?) {
        self.name = name
        self.kind = kind
        self.distanceM = distanceM
        self.description = description
    }
}



extension SearchCandidate: Equatable, Hashable {
    public static func ==(lhs: SearchCandidate, rhs: SearchCandidate) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.distanceM != rhs.distanceM {
            return false
        }
        if lhs.description != rhs.description {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(kind)
        hasher.combine(distanceM)
        hasher.combine(description)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchCandidate: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchCandidate {
        return
            try SearchCandidate(
                name: FfiConverterString.read(from: &buf), 
                kind: FfiConverterString.read(from: &buf), 
                distanceM: FfiConverterOptionDouble.read(from: &buf), 
                description: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: SearchCandidate, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.kind, into: &buf)
        FfiConverterOptionDouble.write(value.distanceM, into: &buf)
        FfiConverterOptionString.write(value.description, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchCandidate_lift(_ buf: RustBuffer) throws -> SearchCandidate {
    return try FfiConverterTypeSearchCandidate.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchCandidate_lower(_ value: SearchCandidate) -> RustBuffer {
    return FfiConverterTypeSearchCandidate.lower(value)
}


/**
 * One ranked forward-search result. `index` points back into the input
 * candidates so the caller can recover position / source / metadata.
 */
public struct SearchHit {
    public var index: UInt64
    public var title: String
    public var description: String?
    public var icon: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(index: UInt64, title: String, description: String?, icon: String) {
        self.index = index
        self.title = title
        self.description = description
        self.icon = icon
    }
}



extension SearchHit: Equatable, Hashable {
    public static func ==(lhs: SearchHit, rhs: SearchHit) -> Bool {
        if lhs.index != rhs.index {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.description != rhs.description {
            return false
        }
        if lhs.icon != rhs.icon {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(index)
        hasher.combine(title)
        hasher.combine(description)
        hasher.combine(icon)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchHit: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchHit {
        return
            try SearchHit(
                index: FfiConverterUInt64.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                description: FfiConverterOptionString.read(from: &buf), 
                icon: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SearchHit, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.index, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterOptionString.write(value.description, into: &buf)
        FfiConverterString.write(value.icon, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchHit_lift(_ buf: RustBuffer) throws -> SearchHit {
    return try FfiConverterTypeSearchHit.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchHit_lower(_ value: SearchHit) -> RustBuffer {
    return FfiConverterTypeSearchHit.lower(value)
}


/**
 * Errors surfaced across the FFI boundary.
 */
public enum EngineError {

    
    
    /**
     * `from_ruleset_json` was given a ruleset that didn't parse.
     */
    case InvalidRuleset(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEngineError: FfiConverterRustBuffer {
    typealias SwiftType = EngineError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EngineError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidRuleset(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: EngineError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InvalidRuleset(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


extension EngineError: Equatable, Hashable {}

extension EngineError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Canonical spatial qualifier (the richer Flutter `LocationQualifier` set).
 * The Android binding folds `CloseTo`→Near and `InArea`→In to match its
 * 4-value `PlaceQualifier`; the UI turns these into localized words.
 */

public enum Qualifier {
    
    /**
     * Standing on the feature (peak / glacier / island).
     */
    case on
    /**
     * Near but outside a point feature (loose peak / farm / water).
     */
    case closeTo
    /**
     * Touching a water body or building.
     */
    case atPlace
    /**
     * Inside a bounded area (settlement / park).
     */
    case inArea
    /**
     * In the wider periphery of a feature.
     */
    case near
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeQualifier: FfiConverterRustBuffer {
    typealias SwiftType = Qualifier

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Qualifier {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .on
        
        case 2: return .closeTo
        
        case 3: return .atPlace
        
        case 4: return .inArea
        
        case 5: return .near
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Qualifier, into buf: inout [UInt8]) {
        switch value {
        
        
        case .on:
            writeInt(&buf, Int32(1))
        
        
        case .closeTo:
            writeInt(&buf, Int32(2))
        
        
        case .atPlace:
            writeInt(&buf, Int32(3))
        
        
        case .inArea:
            writeInt(&buf, Int32(4))
        
        
        case .near:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeQualifier_lift(_ buf: RustBuffer) throws -> Qualifier {
    return try FfiConverterTypeQualifier.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeQualifier_lower(_ value: Qualifier) -> RustBuffer {
    return FfiConverterTypeQualifier.lower(value)
}



extension Qualifier: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDouble: FfiConverterRustBuffer {
    typealias SwiftType = Double?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeAddress: FfiConverterRustBuffer {
    typealias SwiftType = Address?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeAddress.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeAddress.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeKommune: FfiConverterRustBuffer {
    typealias SwiftType = Kommune?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeKommune.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeKommune.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeLocationDescription: FfiConverterRustBuffer {
    typealias SwiftType = LocationDescription?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeLocationDescription.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeLocationDescription.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeProtectedArea: FfiConverterRustBuffer {
    typealias SwiftType = ProtectedArea?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeProtectedArea.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeProtectedArea.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeQualifier: FfiConverterRustBuffer {
    typealias SwiftType = Qualifier?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeQualifier.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeQualifier.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeCandidate: FfiConverterRustBuffer {
    typealias SwiftType = [Candidate]

    public static func write(_ value: [Candidate], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCandidate.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Candidate] {
        let len: Int32 = try readInt(&buf)
        var seq = [Candidate]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCandidate.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSearchCandidate: FfiConverterRustBuffer {
    typealias SwiftType = [SearchCandidate]

    public static func write(_ value: [SearchCandidate], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSearchCandidate.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SearchCandidate] {
        let len: Int32 = try readInt(&buf)
        var seq = [SearchCandidate]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSearchCandidate.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSearchHit: FfiConverterRustBuffer {
    typealias SwiftType = [SearchHit]

    public static func write(_ value: [SearchHit], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSearchHit.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SearchHit] {
        let len: Int32 = try readInt(&buf)
        var seq = [SearchHit]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSearchHit.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_place_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_place_core_checksum_method_placeengine_forward_search() != 27611) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_place_core_checksum_method_placeengine_reverse_geocode() != 17893) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_place_core_checksum_method_placeengine_ruleset_version() != 61736) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_place_core_checksum_constructor_placeengine_from_ruleset_json() != 59077) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_place_core_checksum_constructor_placeengine_with_default_ruleset() != 48803) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all