apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

patches:
  - path: app-config-patch.yaml
  - path: application-patch.yaml

labels:
  - pairs:
      environment: production
      managed-by: k3s
    includeSelectors: true

replicas:
  - name: turboapi-auth
    count: 1
  - name: turboapi-geo
    count: 1
  - name: turboapi-activity
    count: 1
  - name: nats
    count: 1

images:
  - name: turboapi-auth
    newName: ghcr.io/sigmundgranaas/turboapi-auth
    newTag: 1.0.2
  - name: turboapi-geo
    newName: ghcr.io/sigmundgranaas/turboapi-geo
    newTag: 1.0.0
  - name: turboapi-activity
    newName: ghcr.io/sigmundgranaas/turboapi-activity
    newTag: latest