//! Mapbox Vector Tile (MVT) decoder.
//!
//! Spec: <https://github.com/mapbox/vector-tile-spec/tree/master/2.1>
//!
//! The protobuf message types are generated by `prost-build` and consumed
//! internally — this crate exposes higher-level data types (`VectorTile`,
//! `Layer`, `Feature`, `Geometry`) that have already interpreted the
//! geometry command stream and the tag/key/value indirection.

use std::collections::HashMap;

use thiserror::Error;

mod proto {
    include!(concat!(env!("OUT_DIR"), "/vector_tile.rs"));
}

#[derive(Debug, Error)]
pub enum DecodeError {
    #[error("protobuf decode: {0}")]
    Protobuf(#[from] prost::DecodeError),
    #[error("malformed geometry stream: {0}")]
    Geometry(&'static str),
    #[error("layer tags reference out-of-range key/value index")]
    BadTags,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Value {
    String(String),
    Float(f64),
    Int(i64),
    UInt(u64),
    Bool(bool),
    Null,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GeomType {
    Unknown,
    Point,
    LineString,
    Polygon,
}

/// Geometry coordinates are in *tile-local* space — `[0, extent]` on each
/// axis. The caller is responsible for projecting them into world space
/// using the tile id and extent.
#[derive(Debug, Clone, PartialEq)]
pub enum Geometry {
    /// One or more points.
    Point(Vec<(i32, i32)>),
    /// One or more line strings (each is a Vec of vertices).
    LineString(Vec<Vec<(i32, i32)>>),
    /// One or more polygon rings. Multiple polygons are flattened — the
    /// caller can recover them by tracking winding (outer rings are
    /// clockwise, inner rings are counter-clockwise) per the spec.
    Polygon(Vec<Vec<(i32, i32)>>),
}

#[derive(Debug, Clone)]
pub struct Feature {
    pub id: u64,
    pub geom_type: GeomType,
    pub geometry: Geometry,
    pub properties: HashMap<String, Value>,
}

#[derive(Debug, Clone)]
pub struct Layer {
    pub name: String,
    pub version: u32,
    pub extent: u32,
    pub features: Vec<Feature>,
}

#[derive(Debug, Clone)]
pub struct VectorTile {
    pub layers: Vec<Layer>,
}

/// Decode an MVT tile from its protobuf bytes.
pub fn decode(bytes: &[u8]) -> Result<VectorTile, DecodeError> {
    let tile = <proto::Tile as prost::Message>::decode(bytes)?;
    let mut out = VectorTile {
        layers: Vec::with_capacity(tile.layers.len()),
    };
    for raw_layer in tile.layers {
        out.layers.push(decode_layer(raw_layer)?);
    }
    Ok(out)
}

fn decode_layer(raw: proto::tile::Layer) -> Result<Layer, DecodeError> {
    let keys = raw.keys;
    let values: Vec<Value> = raw.values.into_iter().map(decode_value).collect();
    let extent = raw.extent.unwrap_or(4096);

    let mut features = Vec::with_capacity(raw.features.len());
    for raw_feat in raw.features {
        let geom_type = match raw_feat.r#type() {
            proto::tile::GeomType::Unknown => GeomType::Unknown,
            proto::tile::GeomType::Point => GeomType::Point,
            proto::tile::GeomType::Linestring => GeomType::LineString,
            proto::tile::GeomType::Polygon => GeomType::Polygon,
        };
        let geometry = decode_geometry(geom_type, &raw_feat.geometry)?;

        // tags is a flat [key_idx, val_idx, key_idx, val_idx, ...] array.
        if raw_feat.tags.len() % 2 != 0 {
            return Err(DecodeError::BadTags);
        }
        let mut properties = HashMap::with_capacity(raw_feat.tags.len() / 2);
        for pair in raw_feat.tags.chunks_exact(2) {
            let k_idx = pair[0] as usize;
            let v_idx = pair[1] as usize;
            let key = keys.get(k_idx).ok_or(DecodeError::BadTags)?.clone();
            let val = values.get(v_idx).ok_or(DecodeError::BadTags)?.clone();
            properties.insert(key, val);
        }

        features.push(Feature {
            id: raw_feat.id.unwrap_or(0),
            geom_type,
            geometry,
            properties,
        });
    }

    Ok(Layer {
        name: raw.name,
        version: raw.version,
        extent,
        features,
    })
}

fn decode_value(v: proto::tile::Value) -> Value {
    if let Some(s) = v.string_value {
        Value::String(s)
    } else if let Some(f) = v.float_value {
        Value::Float(f as f64)
    } else if let Some(d) = v.double_value {
        Value::Float(d)
    } else if let Some(i) = v.int_value {
        Value::Int(i)
    } else if let Some(u) = v.uint_value {
        Value::UInt(u)
    } else if let Some(s) = v.sint_value {
        Value::Int(s)
    } else if let Some(b) = v.bool_value {
        Value::Bool(b)
    } else {
        Value::Null
    }
}

/// Decode the MVT geometry-command stream into vertex lists. See the spec's
/// "Geometry Encoding" section. Coordinates are tile-local; the caller
/// projects them into world space.
fn decode_geometry(geom_type: GeomType, cmds: &[u32]) -> Result<Geometry, DecodeError> {
    let mut cursor = (0_i32, 0_i32);
    let mut i = 0;
    let mut rings_or_lines: Vec<Vec<(i32, i32)>> = Vec::new();
    let mut current: Vec<(i32, i32)> = Vec::new();
    let mut points: Vec<(i32, i32)> = Vec::new();

    while i < cmds.len() {
        let header = cmds[i];
        i += 1;
        let id = header & 0x7;
        let count = (header >> 3) as usize;
        match id {
            1 => {
                // MoveTo. For LineString/Polygon, MoveTo of count==1 starts a
                // new ring/line. For Point, count >= 1 are the points.
                for _ in 0..count {
                    if i + 1 >= cmds.len() {
                        return Err(DecodeError::Geometry("truncated MoveTo"));
                    }
                    let dx = zigzag_decode(cmds[i]);
                    let dy = zigzag_decode(cmds[i + 1]);
                    i += 2;
                    cursor.0 = cursor.0.wrapping_add(dx);
                    cursor.1 = cursor.1.wrapping_add(dy);
                    match geom_type {
                        GeomType::Point => points.push(cursor),
                        _ => {
                            if !current.is_empty() {
                                rings_or_lines.push(std::mem::take(&mut current));
                            }
                            current.push(cursor);
                        }
                    }
                }
            }
            2 => {
                // LineTo. Append to current ring/line.
                for _ in 0..count {
                    if i + 1 >= cmds.len() {
                        return Err(DecodeError::Geometry("truncated LineTo"));
                    }
                    let dx = zigzag_decode(cmds[i]);
                    let dy = zigzag_decode(cmds[i + 1]);
                    i += 2;
                    cursor.0 = cursor.0.wrapping_add(dx);
                    cursor.1 = cursor.1.wrapping_add(dy);
                    current.push(cursor);
                }
            }
            7 => {
                // ClosePath — only valid for polygons. Close the current ring.
                if !current.is_empty() {
                    let first = current[0];
                    if current.last() != Some(&first) {
                        current.push(first);
                    }
                    rings_or_lines.push(std::mem::take(&mut current));
                }
            }
            _ => return Err(DecodeError::Geometry("unknown geometry command id")),
        }
    }
    if !current.is_empty() {
        rings_or_lines.push(current);
    }

    Ok(match geom_type {
        GeomType::Point => Geometry::Point(points),
        GeomType::LineString => Geometry::LineString(rings_or_lines),
        GeomType::Polygon => Geometry::Polygon(rings_or_lines),
        GeomType::Unknown => Geometry::Point(Vec::new()),
    })
}

/// MVT uses zigzag varint encoding for signed coordinate deltas.
/// `n` is the raw uint32 from the command stream.
fn zigzag_decode(n: u32) -> i32 {
    ((n >> 1) as i32) ^ -((n & 1) as i32)
}

#[cfg(test)]
mod tests {
    //! Value boundary: a developer wraps MVT bytes (from HTTP, PMTiles, disk)
    //! and expects to walk layers/features/geometry without ever touching
    //! protobuf or the MVT command stream. The decoder must (a) round-trip
    //! through prost's encoder so the wire format is faithful, (b) interpret
    //! zigzag and the MoveTo/LineTo/ClosePath stream correctly.
    use super::*;
    use prost::Message as _;

    #[test]
    fn zigzag_known_values() {
        // Spec examples.
        assert_eq!(zigzag_decode(0), 0);
        assert_eq!(zigzag_decode(1), -1);
        assert_eq!(zigzag_decode(2), 1);
        assert_eq!(zigzag_decode(3), -2);
        assert_eq!(zigzag_decode(4), 2);
        // Min/max edges.
        assert_eq!(zigzag_decode(0xFFFF_FFFE), i32::MAX);
        assert_eq!(zigzag_decode(0xFFFF_FFFF), i32::MIN);
    }

    #[test]
    fn geometry_command_stream_decodes_a_simple_line() {
        // LineString from (3, 6) → (8, 12) → (20, 34).
        // Header MoveTo count=1:  (1 << 3) | 1 = 9
        // dx=3, dy=6 (zigzag: 6, 12)
        // Header LineTo count=2:  (2 << 3) | 2 = 18
        // (3,6)→(8,12): dx=5, dy=6 (zigzag: 10, 12)
        // (8,12)→(20,34): dx=12, dy=22 (zigzag: 24, 44)
        let cmds = [9_u32, 6, 12, 18, 10, 12, 24, 44];
        let geom = decode_geometry(GeomType::LineString, &cmds).unwrap();
        match geom {
            Geometry::LineString(lines) => {
                assert_eq!(lines.len(), 1);
                assert_eq!(lines[0], vec![(3, 6), (8, 12), (20, 34)]);
            }
            _ => panic!("expected LineString"),
        }
    }

    #[test]
    fn geometry_stream_decodes_a_closed_polygon_ring() {
        // Triangle: (5, 5) → (10, 5) → (10, 10) → close.
        // MoveTo count=1 at (5,5): header=9, dx=5(10), dy=5(10)
        // LineTo count=2: header=18, then (10,5):(5,0)→10,0;  (10,10):(0,5)→0,10
        // ClosePath count=1: header = (1<<3) | 7 = 15
        let cmds = [9_u32, 10, 10, 18, 10, 0, 0, 10, 15];
        let geom = decode_geometry(GeomType::Polygon, &cmds).unwrap();
        match geom {
            Geometry::Polygon(rings) => {
                assert_eq!(rings.len(), 1);
                let ring = &rings[0];
                assert_eq!(ring.first(), Some(&(5, 5)));
                assert_eq!(ring.last(), Some(&(5, 5)), "ClosePath must wrap back");
                assert_eq!(ring.len(), 4); // 3 unique + 1 closing
            }
            _ => panic!("expected Polygon"),
        }
    }

    #[test]
    fn round_trip_through_prost_yields_the_same_layers_and_features() {
        // Hand-build a minimal Tile via the prost-generated types, encode it,
        // run our public `decode`, and check we see what we put in.
        // One layer "places" with one Point feature {name: "Bergen"} at
        // (123, 456).
        let layer = proto::tile::Layer {
            version: 2,
            name: "places".into(),
            features: vec![proto::tile::Feature {
                id: Some(42),
                tags: vec![0, 0], // key 0 = "name", value 0 = String("Bergen")
                r#type: Some(proto::tile::GeomType::Point as i32),
                // MoveTo count=1, dx=123 zigzag=246, dy=456 zigzag=912
                geometry: vec![9, 246, 912],
            }],
            keys: vec!["name".into()],
            values: vec![proto::tile::Value {
                string_value: Some("Bergen".into()),
                ..Default::default()
            }],
            extent: Some(4096),
        };
        let tile = proto::Tile {
            layers: vec![layer],
        };
        let bytes = tile.encode_to_vec();

        let decoded = decode(&bytes).unwrap();
        assert_eq!(decoded.layers.len(), 1);
        let l = &decoded.layers[0];
        assert_eq!(l.name, "places");
        assert_eq!(l.extent, 4096);
        assert_eq!(l.features.len(), 1);
        let f = &l.features[0];
        assert_eq!(f.id, 42);
        assert_eq!(f.geom_type, GeomType::Point);
        assert_eq!(f.geometry, Geometry::Point(vec![(123, 456)]));
        assert_eq!(
            f.properties.get("name"),
            Some(&Value::String("Bergen".into()))
        );
    }
}
