name: Build and Release Flutter App

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: 'stable'
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Extract app version
        id: get_version
        run: |
          # The grep command finds the line with "version:", and cut splits the line
          # and gets the second field, which is the version number.
          VERSION=$(grep '^version:' pubspec.yaml | cut -d ' ' -f 2)
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.APP_VERSION }}

          # The title of the release.
          name: Release ${{ env.APP_VERSION }}

          generate_release_notes: true

          files: build/app/outputs/flutter-apk/app-release.apk